/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */

/**
 * Order-workbench pure functions (Order Create/View UI, T3).
 *
 * These carry the business math for the workbench service and are unit-tested
 * directly (no DB). Keep them side-effect free: the service composes them, the
 * action wrappers stay thin.
 */

import {
  ORDER_LIFECYCLE_STATUSES,
  requireOrderLifecycleStatus,
  type OrderLifecycleStatus,
} from '../../order-planning/order-lifecycle-status';
import type { OrderWorkflowStage } from '../../order-planning/order-operational-status';

export const MAX_ORDER_REF_LENGTH = 40;

/**
 * Gross margin percent from sell price and unit cost, e.g. sell 20 / cost 15 → 25.
 * Deliberately gross-of-fees: the silver sheet's own "Exp. Margin" (net of Amazon
 * fees) always wins when present; this is only the fallback when the operator gives
 * a sell price and cost but no explicit margin. Returned in the same "percent number"
 * unit the importer stores (12.2 means 12.2%). Rounded to one decimal.
 */
export function computeLineMargin(input: { expectedSellPrice?: number; unitCost?: number }): number | undefined {
  const sell = finiteNumber(input.expectedSellPrice);
  const cost = finiteNumber(input.unitCost);
  if (sell === undefined || cost === undefined || sell <= 0) return undefined;
  return round1(((sell - cost) / sell) * 100);
}

/** Line expected cost = ordered quantity × unit cost. Undefined when unit cost is absent. */
export function computeLineExpectedCost(input: { orderedQty?: number; unitCost?: number }): number | undefined {
  const qty = finiteNumber(input.orderedQty);
  const cost = finiteNumber(input.unitCost);
  if (qty === undefined || cost === undefined) return undefined;
  return round2(qty * cost);
}

/** Header expected cost = sum of line expected costs. Undefined when no line has a cost. */
export function sumExpectedCost(lines: Array<{ orderedQty?: number; unitCost?: number }>): number | undefined {
  let total = 0;
  let seen = false;
  for (const line of lines) {
    const lineCost = computeLineExpectedCost(line);
    if (lineCost === undefined) continue;
    total += lineCost;
    seen = true;
  }
  return seen ? round2(total) : undefined;
}

/** Trim + uppercase an operator-entered order ref; returns the empty string if blank. */
export function normalizeOrderRef(value: unknown): string {
  return typeof value === 'string' ? value.trim().toUpperCase() : '';
}

/** Validate a normalized ref: non-empty and ≤ MAX_ORDER_REF_LENGTH. Throws with a clear message. */
export function requireValidOrderRef(value: unknown): string {
  const normalized = normalizeOrderRef(value);
  if (!normalized) throw new Error('Order reference is required.');
  if (normalized.length > MAX_ORDER_REF_LENGTH) {
    throw new Error(`Order reference must be ${MAX_ORDER_REF_LENGTH} characters or fewer.`);
  }
  return normalized;
}

/**
 * The trailing sequence letter to store on `dailySequenceLetter` when the ref matches
 * the canonical `<companyKey><MMDDYY><letter>` shape generated by generateOrderRef;
 * otherwise the whole (operator-edited) ref, so the (companyId, orderDate,
 * dailySequenceLetter) unique index still holds for arbitrary refs.
 */
export function trailingSequenceLetter(orderRef: string, companyKey: string, orderDate: string): string {
  const ref = normalizeOrderRef(orderRef);
  const mmddyy = canonicalDateToken(orderDate);
  if (companyKey && mmddyy) {
    const prefix = `${companyKey.toUpperCase()}${mmddyy}`;
    const remainder = ref.startsWith(prefix) ? ref.slice(prefix.length) : '';
    if (/^[A-Z]$/.test(remainder)) return remainder;
  }
  return ref;
}

/** `2026-07-24` → `072426` (MMDDYY), matching generateOrderRef. Empty string when unparseable. */
export function canonicalDateToken(orderDate: string): string {
  const match = /^(\d{4})-(\d{2})-(\d{2})/.exec(String(orderDate ?? ''));
  if (!match) return '';
  const [, year, month, day] = match;
  return `${month}${day}${year.slice(2)}`;
}

/**
 * Deterministic map from an operator-picked lifecycle status (one of the 11 canonical
 * labels) to the {canonicalStatus, workflowStage} the gold engine consumes. Derived
 * from OPERATIONAL_STATUS_METADATA where a clean mapping exists; the two lifecycle
 * labels with no ClickUp source (AT PREP NOT STARTED, SHIPPED TO FBA) are mapped to
 * their neighbouring after-ordered semantics. canonicalStatus feeds the supplier-order
 * status buckets (placedNotPurchased / purchasedPipeline / closed); workflowStage feeds
 * existingOrderStage (pre_purchase / in_prep / inbound → activeOrders / inPrep / inbound).
 */
export const LIFECYCLE_STATUS_ENGINE_MAP: Record<
  OrderLifecycleStatus,
  { canonicalStatus: string; workflowStage: OrderWorkflowStage }
> = {
  'IN-PROGRESS': { canonicalStatus: 'supplier_contacted', workflowStage: 'pre_purchase' },
  'ORDER ANALYSING': { canonicalStatus: 'draft', workflowStage: 'pre_purchase' },
  'APPROVED TO ORDER': { canonicalStatus: 'payment_pending', workflowStage: 'pre_purchase' },
  ORDERED: { canonicalStatus: 'paid', workflowStage: 'in_prep' },
  'IN TRANSIT TO PREP': { canonicalStatus: 'paid', workflowStage: 'in_prep' },
  'DIRECT SHIP FBA': { canonicalStatus: 'shipped_inbound', workflowStage: 'amazon_inbound' },
  'AT PREP NOT STARTED': { canonicalStatus: 'paid', workflowStage: 'in_prep' },
  'PREP IN-PROGRESS': { canonicalStatus: 'paid', workflowStage: 'in_prep' },
  'SHIPPED TO FBA': { canonicalStatus: 'shipped_inbound', workflowStage: 'amazon_inbound' },
  'INBOUND MONITORING': { canonicalStatus: 'shipped_inbound', workflowStage: 'amazon_inbound' },
  COMPLETE: { canonicalStatus: 'completed', workflowStage: 'complete' },
};

export interface StatusWrite {
  lifecycleStatus: OrderLifecycleStatus;
  canonicalStatus: string;
  workflowStage: OrderWorkflowStage;
}

/** Resolve an operator status pick to the full {lifecycle, canonical, workflowStage} write set. */
export function deriveStatusWrite(value: unknown): StatusWrite {
  const lifecycleStatus = requireOrderLifecycleStatus(value, 'Ecobase order workbench setOrderStatus');
  const engine = LIFECYCLE_STATUS_ENGINE_MAP[lifecycleStatus];
  return { lifecycleStatus, canonicalStatus: engine.canonicalStatus, workflowStage: engine.workflowStage };
}

export const ORDER_LIFECYCLE_STATUS_SET: ReadonlySet<string> = new Set(ORDER_LIFECYCLE_STATUSES);

function finiteNumber(value: unknown): number | undefined {
  return typeof value === 'number' && Number.isFinite(value) ? value : undefined;
}

function round1(value: number): number {
  return Math.round(value * 10) / 10;
}

function round2(value: number): number {
  return Math.round(value * 100) / 100;
}
