/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */

/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Team.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */

import Decimal from 'decimal.js';

export const OBSOLETE_INVENTORY_PLANNING_ROW_FIELDS = [
  'planningProductId',
  'tier',
  'tierScore',
  'recentUnits30',
  'tierEligibilityReason',
  'tierRuleVersion',
  'currentTier',
  'currentTierScore',
  'averageTier',
  'averageTierScore',
  'bestTier',
  'bestTierScore',
  'previousTier',
  'tierMovement',
  'profitPerUnit',
  'lastMonthQty',
  'sixMonthAverageQty',
  'sixMonthWorstQty',
  'sixMonthBestQty',
  'sixMonthMargin',
  'recommendedBestQty',
  'suggestedReorderQty',
  'stuck',
  'stuckClassification',
  'commandCenterPane',
  'commandCenterPaneReason',
  'planningEligibilityStatus',
  'planningEligibilityReason',
  'familyAmazonAccountId',
  'familyMarketplace',
  'familyCanonicalAsin',
  'familyRole',
  'familyMemberCount',
  'replenishmentTargetCompanyProductId',
  'replenishmentTargetSku',
  'familyTier',
  'familyTierScore',
  'familyCurrentPlanningStock',
  'familyOnHandStock',
  'familyOnHandSellableStock',
  'familyAmazonPipelineStock',
  'familySupplierPipelineStock',
  'familyInventoryPositionStock',
  'familyFuturePositionStock',
  'familySellableStock',
  'familyReservedStock',
  'familyPipelineStock',
  'familyInboundStock',
  'familyOrderedStock',
  'familyPrepStock',
  'familyAwdStock',
  'familySalesVelocity',
  'familyDaysOfCover',
  'familyEstimatedOosDate',
  'familyPositionDaysOfCover',
  'familyPositionEstimatedOosDate',
  'familyOpenOrderCoverageQty',
  'familyTrustedSupplierOrderCoverageQty',
  'familySuggestedReorderQty',
  'familyPreferredSupplierId',
  'familyPreferredSupplierProductId',
  'familyPreferredSupplierName',
  'familyUnitCost',
  'familyLeadTimeDays',
  'familyEstimatedOrderCost',
  'familyStuck',
  'familyStuckAction',
  'familyStuckClassification',
  'familyStuckAffectedMemberCount',
  'familyStuckAffectedUnits',
  'familyStuckAffectedValue',
  'familyStuckActiveOrderCount',
  'familyStuckEvidence',
  'familyRollupEvidence',
] as const;

export const CORRECTED_INVENTORY_PLANNING_ROW_FIELDS = [
  'companyProductId',
  'companyProductFamilyId',
  'companyId',
  'amazonAccountId',
  'marketplace',
  'ruleVersion',
  'algorithmContractVersion',
  'currentProjectionGateMode',
  'resolvedPlanningSettingsDigest',
  'sourceCoverageDigest',
  'sourceInputDigest',
  'protectedSilverFingerprint',
  'candidateInputDigest',
  'productCoverageDigest',
  'sourceAsOfDate',
  'baselineWindowStartDate',
  'baselineWindowEndDate',
  'baselineEligibleMonthCount',
  'baselineConfidence',
  'monthlyPerformanceEvidence',
  'baselineTotalUnits',
  'baselineTotalProfit',
  'baselineWeightedProfitPerUnit',
  'averageMonthlyUnits',
  'averageMonthlyProfit',
  'baselineTierScore',
  'baselineTier',
  'baselineState',
  'baselineReasonCodes',
  'bestMonthlyUnits',
  'bestUnitsMonth',
  'bestMonthlyProfit',
  'bestProfitMonth',
  'worstMonthlyUnits',
  'worstUnitsMonth',
  'worstMonthlyProfit',
  'worstProfitMonth',
  'lastClosedMonth',
  'lastClosedMonthUnits',
  'lastClosedMonthProfit',
  'lastClosedMonthTierScore',
  'lastClosedMonthTier',
  'lastClosedMonthState',
  'lastClosedMonthReasonCodes',
  'currentMonthStartDate',
  'currentCoverageEndDate',
  'currentCoveredDays',
  'currentMonthUnits',
  'currentMonthProfit',
  'projectedMonthlyUnits',
  'projectedMonthlyProfit',
  'currentProjectedTierScore',
  'currentProjectedTier',
  'currentProjectedState',
  'currentProjectionConfidence',
  'currentProjectionReasonCodes',
  'closedTierMovement',
  'projectedTierMovement',
  'trendReasonCodes',
  'expectedAverageUnitsMtd',
  'expectedBestUnitsMtd',
  'expectedWorstUnitsMtd',
  'expectedAverageProfitMtd',
  'expectedBestProfitMtd',
  'expectedWorstProfitMtd',
  'quantityPaceStatus',
  'profitPaceStatus',
  'aggregatePaceStatus',
  'paceCause',
  'paceEvidence',
  'rollingUnits30',
  'rollingVelocityWindowStartDate',
  'rollingVelocityWindowEndDate',
  'rollingVelocityEvidenceStatus',
  'inventoryDisposition',
  'inventoryDispositionReasonCode',
  'replenishmentEligibility',
  'replenishmentBlockReasonCode',
  'newReplenishmentActionable',
  'oosAlertActionable',
  'supplyActionable',
  'recommendedOrderQty',
  'existingOrderFollowUp',
  'existingOrderFollowUpAction',
  'primaryActionPane',
  'primaryActionReasonCode',
  'isFrozenFamilyTarget',
  'familyTargetCompanyProductId',
  'listingReviewCategories',
  'calculationEvidence',
  'calculationProvenanceJson',
  'calculationDate',
  'company',
  'asin',
  'sku',
  'title',
  'brand',
  'productStatus',
  'planningExcluded',
  'actionStatus',
  'estimatedProfitRisk',
  'estimatedProfitRiskBasis',
  'moneyRiskStatus',
  'moneyRiskUncoveredDays',
  'moneyRiskInputs',
  'unitCost',
  'unitCostSource',
  'supplierAvailability',
  'leadTimeAvailability',
  'unitCostAvailability',
  'profitAvailability',
  'estimatedOrderCost',
  'salesVelocity',
  'salesVelocityBasis',
  'salesVelocityStatus',
  'salesVelocityWindowStart',
  'salesVelocityWindowEnd',
  'salesVelocityAsOfDate',
  'safetyBufferDays',
  'reorderCycleDays',
  'targetCoverDays',
  'orderSoonWindowDays',
  'leadTimeFreshnessDays',
  'purchasedPipelineGraceDays',
  'currentPlanningStock',
  'onHandStock',
  'onHandSellableStock',
  'amazonPipelineStock',
  'supplierPipelineStock',
  'inventoryPositionStock',
  'futurePositionStock',
  'sellableStock',
  'reservedStock',
  'pipelineStock',
  'inboundStock',
  'orderedStock',
  'prepStock',
  'awdStock',
  'openOrderCoverageQty',
  'trustedSupplierOrderCoverageQty',
  'supplierOrderState',
  'supplierOrderStale',
  'supplierOrderId',
  'supplierOrderStatus',
  'supplierOrderOperationalStatus',
  'supplierOrderWorkflowStage',
  'supplierOrderSourceMemberSku',
  'supplierOrderLineMappingScope',
  'supplierOrderRef',
  'supplierOrderAuthorityStatus',
  'supplierOrderAuthoritySource',
  'supplierOrderAuthorityTaskRef',
  'supplierOrderAuthorityAsOf',
  'supplierOrderAuthorityEvidence',
  'amazonReceiptStatus',
  'amazonReceiptObservedAt',
  'amazonReceiptCompletionReason',
  'amazonReceiptEvidenceJson',
  'supplierOrderOpenQty',
  'supplierOrderReferenceOpenQty',
  'supplierOrderCycleSelection',
  'supplierOrderCycleReviewRequired',
  'supplierOrderPurchasedOpenQty',
  'supplierOrderPlacedNotPurchasedOpenQty',
  'pipelineHealthStatus',
  'stockoutGapDays',
  'dataQualityStatus',
  'dataQualityIssues',
  'readinessDomains',
  'readinessReasonCodes',
  'operationalIssues',
  'inventoryAsOfDate',
  'sourceFreshnessStatus',
  'latestSupplierOrderActivityType',
  'latestSupplierOrderActivityAt',
  'latestSupplierOrderActivityNote',
  'latestSupplierOrderActivityActor',
  'latestSupplierOrderActivityActorUserId',
  'latestSupplierOrderActivityActorDisplayName',
  'latestSupplierOrderActivityActorEmail',
  'latestSupplierOrderActivitySource',
  'recommendedEscalation',
  'daysOfCover',
  'estimatedOosDate',
  'daysUntilOos',
  'positionDaysOfCover',
  'positionEstimatedOosDate',
  'latestSafeReorderDate',
  'daysUntilSafeReorder',
  'supplierId',
  'supplierName',
  'supplierSource',
  'supplierRole',
  'supplierConfidence',
  'leadTimeDays',
  'leadTimeConfirmedAt',
  'leadTimeFreshness',
  'expectedArrivalDate',
  'expectedArrivalStatus',
  'expectedArrivalSource',
  'expectedArrivalAsOf',
  'expectedArrivalConfidence',
  'expectedArrivalFreshness',
  'digestPriority',
  'evidence',
] as const;

const DIGEST_DOUBLE_FIELDS = new Set(['daysOfCover', 'pipelineStock', 'reservedStock', 'salesVelocity']);
const DIGEST_DECIMAL8_FIELDS = new Set(['recommendedOrderQty']);
const DigestDecimal = Decimal.clone({ precision: 40, rounding: Decimal.ROUND_HALF_EVEN });

export function normalizeCorrectedInventoryPlanningDigestValue(field: string, value: unknown) {
  if (value === null || value === undefined) return null;
  if (DIGEST_DOUBLE_FIELDS.has(field)) {
    if (value === '' || (typeof value !== 'number' && typeof value !== 'string')) {
      throw new Error(`EcoBase corrected digest requires ${field} as a finite number.`);
    }
    const normalized = Number(value);
    if (!Number.isFinite(normalized)) {
      throw new Error(`EcoBase corrected digest requires ${field} as a finite number.`);
    }
    return normalized;
  }
  if (DIGEST_DECIMAL8_FIELDS.has(field)) {
    let normalized: Decimal;
    try {
      normalized = new DigestDecimal(String(value));
    } catch {
      throw new Error(`EcoBase corrected digest requires ${field} as a finite decimal8 value.`);
    }
    if (!normalized.isFinite()) {
      throw new Error(`EcoBase corrected digest requires ${field} as a finite decimal8 value.`);
    }
    return normalized.toDecimalPlaces(8, DigestDecimal.ROUND_HALF_EVEN).toFixed(8);
  }
  return value;
}

export function correctedInventoryPlanningDigestProjection(row: Readonly<Record<string, unknown>>) {
  return {
    naturalKey: row.naturalKey ?? null,
    ...Object.fromEntries(
      CORRECTED_INVENTORY_PLANNING_ROW_FIELDS.map((field) => [
        field,
        normalizeCorrectedInventoryPlanningDigestValue(field, row[field]),
      ]),
    ),
  };
}

const OBSOLETE_INVENTORY_PLANNING_ROW_FIELD_SET = new Set<string>(OBSOLETE_INVENTORY_PLANNING_ROW_FIELDS);

export function omitObsoleteInventoryPlanningRowFields<T extends Record<string, unknown>>(row: T) {
  return Object.fromEntries(
    Object.entries(row).filter(([name]) => !OBSOLETE_INVENTORY_PLANNING_ROW_FIELD_SET.has(name)),
  );
}
