import { defineCollection } from '@nocobase/database';
import { ECOBASE_COLLECTIONS } from './names';

export default defineCollection({
  migrationRules: ['schema-only'],
  autoGenId: false,
  name: ECOBASE_COLLECTIONS.alerts,
  title: 'Ecobase alerts',
  fields: [
    { name: 'id', type: 'uuid', interface: 'input', uiSchema: { title: 'ID' }, primaryKey: true },
    {
      name: 'dedupeKey',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Dedupe Key' },
      allowNull: false,
      unique: true,
    },
    {
      name: 'planningProductId',
      type: 'uuid',
      interface: 'input',
      uiSchema: { title: 'Planning Product ID' },
      autoFill: false,
      index: true,
    },
    { name: 'company', type: 'string', interface: 'input', uiSchema: { title: 'Company' }, index: true },
    { name: 'canonicalAsin', type: 'string', interface: 'input', uiSchema: { title: 'Canonical ASIN' }, index: true },
    { name: 'title', type: 'string', interface: 'input', uiSchema: { title: 'Title' } },
    {
      name: 'alertEvaluationId',
      type: 'uuid',
      interface: 'input',
      uiSchema: { title: 'Alert Evaluation ID' },
      autoFill: false,
      index: true,
    },
    {
      name: 'alertType',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Alert Type' },
      allowNull: false,
      index: true,
    },
    {
      name: 'severity',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Severity' },
      allowNull: false,
      index: true,
    },
    {
      name: 'status',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Status' },
      allowNull: false,
      defaultValue: 'open',
      index: true,
    },
    {
      name: 'subjectRef',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Subject Ref' },
      allowNull: false,
      index: true,
    },
    {
      name: 'primaryRootCauseCode',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Primary Root Cause Code' },
      allowNull: false,
      index: true,
    },
    {
      name: 'actionRequired',
      type: 'text',
      interface: 'textarea',
      uiSchema: { title: 'Action Required' },
      allowNull: false,
    },
    { name: 'rootCauses', type: 'jsonb', interface: 'json', uiSchema: { title: 'Root Causes' }, defaultValue: [] },
    { name: 'dataWarnings', type: 'jsonb', interface: 'json', uiSchema: { title: 'Data Warnings' }, defaultValue: [] },
    { name: 'evidence', type: 'jsonb', interface: 'json', uiSchema: { title: 'Evidence' }, defaultValue: {} },
    {
      name: 'openedAt',
      type: 'datetimeTz',
      interface: 'datetime',
      uiSchema: { title: 'Opened At' },
      allowNull: false,
      index: true,
    },
    {
      name: 'lastSeenAt',
      type: 'datetimeTz',
      interface: 'datetime',
      uiSchema: { title: 'Last Seen At' },
      allowNull: false,
      index: true,
    },
    { name: 'resolvedAt', type: 'datetimeTz', interface: 'datetime', uiSchema: { title: 'Resolved At' }, index: true },
  ],
});
