import { defineCollection } from '@nocobase/database';
import { ECOBASE_COLLECTIONS } from './names';

const numberField = (name: string, title: string, index = false) => ({
  name,
  type: 'double',
  interface: 'number',
  uiSchema: { title },
  index,
});

const integerField = (name: string, title: string, index = false) => ({
  name,
  type: 'integer',
  interface: 'integer',
  uiSchema: { title },
  index,
});

export default defineCollection({
  migrationRules: ['schema-only'],
  loadedFromCollectionManager: true,
  autoGenId: false,
  name: ECOBASE_COLLECTIONS.dailyManagementSnapshots,
  title: 'Daily management snapshots',
  indexes: [{ unique: true, fields: ['snapshotDate', 'companyScope'] }],
  fields: [
    { name: 'id', type: 'uuid', interface: 'input', uiSchema: { title: 'ID' }, primaryKey: true },
    { name: 'snapshotDate', type: 'dateOnly', interface: 'date', uiSchema: { title: 'Snapshot Date' }, index: true },
    { name: 'company', type: 'string', interface: 'input', uiSchema: { title: 'Company' }, index: true },
    { name: 'companyScope', type: 'string', interface: 'input', uiSchema: { title: 'Company Scope' }, index: true },
    { name: 'reportRunId', type: 'uuid', interface: 'input', uiSchema: { title: 'Report Run ID' }, index: true },
    {
      name: 'generatedAt',
      type: 'datetimeTz',
      interface: 'datetime',
      uiSchema: { title: 'Generated At' },
      index: true,
    },
    numberField('inventoryMoneyAtRisk', 'Inventory Money At Risk', true),
    integerField('urgentInventorySkuCount', 'Urgent Inventory SKU Count', true),
    integerField('overdueInventorySkuCount', 'Overdue Inventory SKU Count'),
    integerField('aTierInventoryRiskCount', 'A-tier Inventory Risk Count'),
    integerField('next7DayOosSkuCount', 'Next 7-Day OOS SKU Count'),
    {
      name: 'earliestOosDate',
      type: 'dateOnly',
      interface: 'date',
      uiSchema: { title: 'Earliest OOS Date' },
      index: true,
    },
    numberField('weightedDaysOfCover', 'Weighted Days Of Cover'),
    integerField('untrustedCoverageSkuCount', 'Untrusted Coverage SKU Count'),
    integerField('missingLeadTimeCount', 'Missing Lead Time Count'),
    integerField('staleLeadTimeCount', 'Stale Lead Time Count'),
    numberField('orderMoneyAtRisk', 'Order Money At Risk', true),
    integerField('ordersNeedingCheck', 'Orders Needing Check', true),
    integerField('staleOrderCount', 'Stale Order Count'),
    integerField('openOrderActionCount', 'Open Order Action Count'),
    numberField('supplierAttentionMoneyAtRisk', 'Supplier Attention Money At Risk'),
    integerField('supplierAttentionCount', 'Supplier Attention Count'),
    integerField('dataWarningCount', 'Data Warning Count'),
    integerField('staleSourceCount', 'Stale Source Count'),
    integerField('fallbackMappingCount', 'Fallback Mapping Count'),
    integerField('todayActionCount', 'Today Action Count', true),
    integerField('buyBoxRiskCount', 'Buy Box Risk Count'),
    integerField('performanceTrendCount', 'Performance Trend Count'),
    integerField('targetOffTrackCount', 'Target Off Track Count'),
    numberField('sales7d', '7-Day Sales'),
    numberField('profit7d', '7-Day Profit'),
    numberField('units7d', '7-Day Units'),
    numberField('margin7d', '7-Day Margin'),
    numberField('refundRate7d', '7-Day Refund Rate'),
    numberField('buyBoxPct7d', '7-Day Buy Box %'),
    numberField('conversionRate7d', '7-Day Conversion Rate'),
    {
      name: 'snapshotPayload',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Snapshot Payload' },
      defaultValue: {},
    },
  ],
});
