import { defineCollection } from '@nocobase/database';
import { ECOBASE_COLLECTIONS } from './names';

export default defineCollection({
  migrationRules: ['schema-only'],
  autoGenId: false,
  name: ECOBASE_COLLECTIONS.goldSupplierAttentionRows,
  title: 'Gold supplier attention rows',
  fields: [
    { name: 'id', type: 'uuid', primaryKey: true },
    { name: 'naturalKey', type: 'string', allowNull: false, unique: true },
    { name: 'calculationDate', type: 'dateOnly', index: true },
    { name: 'supplierName', type: 'string', index: true },
    { name: 'companyId', type: 'uuid', autoFill: false, index: true },
    { name: 'companyName', type: 'string', index: true },
    {
      name: 'supplier',
      type: 'belongsTo',
      target: ECOBASE_COLLECTIONS.silverSuppliers,
      foreignKey: 'supplierId',
      targetKey: 'id',
      onDelete: 'CASCADE',
    },
    {
      name: 'companyProduct',
      type: 'belongsTo',
      target: ECOBASE_COLLECTIONS.silverCompanyProducts,
      foreignKey: 'companyProductId',
      targetKey: 'id',
      onDelete: 'SET NULL',
    },
    {
      name: 'order',
      type: 'belongsTo',
      target: ECOBASE_COLLECTIONS.silverOrders,
      foreignKey: 'orderId',
      targetKey: 'id',
      onDelete: 'SET NULL',
    },
    { name: 'priority', type: 'string', allowNull: false },
    { name: 'lifecycleStatus', type: 'string', index: true },
    { name: 'followUpState', type: 'string', index: true },
    { name: 'nextFollowUpAt', type: 'datetimeTz' },
    { name: 'lastContactedAt', type: 'datetimeTz' },
    { name: 'lastComment', type: 'text' },
    { name: 'latestCommentAt', type: 'datetimeTz' },
    { name: 'moneyAtRisk', type: 'double' },
    { name: 'inventoryMoneyAtRisk', type: 'double' },
    { name: 'orderMoneyAtRisk', type: 'double' },
    { name: 'staleOrderCount', type: 'integer' },
    { name: 'leadTimeIssueCount', type: 'integer' },
    { name: 'candidateProductCount', type: 'integer' },
    { name: 'approvedProductCount', type: 'integer' },
    { name: 'accountStatus', type: 'string' },
    { name: 'priorityScore', type: 'double', index: true },
    { name: 'recommendedAction', type: 'text', allowNull: false },
    { name: 'evidenceJson', type: 'jsonb', defaultValue: {} },
  ],
});
