/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */

import { defineCollection } from '@nocobase/database';
import { ECOBASE_COLLECTIONS } from './names';

const ACTION_STATUS_OPTIONS = [
  { label: 'Overdue', value: 'overdue', color: 'red' },
  { label: 'Order today', value: 'order_today', color: 'volcano' },
  { label: 'Order soon', value: 'order_soon', color: 'orange' },
  { label: 'Missing lead time', value: 'missing_lead_time', color: 'gold' },
  { label: 'Stale lead time', value: 'stale_lead_time', color: 'orange' },
  { label: 'Already ordered', value: 'already_ordered', color: 'blue' },
  { label: 'Watch', value: 'watch', color: 'cyan' },
  { label: 'Sufficient stock', value: 'sufficient_stock', color: 'green' },
  { label: 'No sell-through', value: 'no_sell_through', color: 'purple' },
  { label: 'Excluded', value: 'excluded', color: 'default' },
];

const TIER_OPTIONS = [
  { label: 'A', value: 'A', color: 'red' },
  { label: 'B', value: 'B', color: 'orange' },
  { label: 'C', value: 'C', color: 'blue' },
  { label: 'Unclassified', value: 'unclassified', color: 'default' },
];

const LEAD_TIME_FRESHNESS_OPTIONS = [
  { label: 'Fresh', value: 'fresh', color: 'green' },
  { label: 'Default (30 days)', value: 'default', color: 'blue' },
  { label: 'Stale', value: 'stale', color: 'orange' },
  { label: 'Missing', value: 'missing', color: 'red' },
];

const SUPPLIER_ORDER_STATE_OPTIONS = [
  { label: 'No order history', value: 'no_open_order', color: 'red' },
  { label: 'No open order', value: 'closed_history', color: 'default' },
  { label: 'Order placed, not purchased', value: 'placed_not_purchased', color: 'orange' },
  { label: 'Purchased / pipeline', value: 'purchased_pipeline', color: 'blue' },
];

export default defineCollection({
  migrationRules: ['schema-only'],
  loadedFromCollectionManager: true,
  autoGenId: false,
  name: ECOBASE_COLLECTIONS.goldInventoryPlanningRows,
  title: 'Gold inventory planning rows',
  fields: [
    { name: 'id', type: 'uuid', interface: 'input', uiSchema: { title: 'ID' }, primaryKey: true },
    {
      name: 'naturalKey',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Natural Key' },
      allowNull: false,
      unique: true,
    },
    {
      name: 'planningProductId',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Planning Product ID' },
      index: true,
    },
    {
      name: 'companyProduct',
      type: 'belongsTo',
      target: ECOBASE_COLLECTIONS.silverCompanyProducts,
      foreignKey: 'companyProductId',
      targetKey: 'id',
      onDelete: 'CASCADE',
    },
    {
      name: 'companyProductFamily',
      type: 'belongsTo',
      target: ECOBASE_COLLECTIONS.silverCompanyProductFamilies,
      foreignKey: 'companyProductFamilyId',
      targetKey: 'id',
      onDelete: 'SET NULL',
    },
    { name: 'familyMarketplace', type: 'string', interface: 'input', uiSchema: { title: 'Family Marketplace' } },
    { name: 'familyCanonicalAsin', type: 'string', interface: 'input', uiSchema: { title: 'Family ASIN' } },
    { name: 'familyRole', type: 'string', interface: 'input', uiSchema: { title: 'Family Role' }, index: true },
    { name: 'familyMemberCount', type: 'integer', interface: 'integer', uiSchema: { title: 'Family Members' } },
    {
      name: 'replenishmentTargetCompanyProductId',
      type: 'uuid',
      interface: 'input',
      uiSchema: { title: 'Replenishment Target' },
      index: true,
    },
    { name: 'replenishmentTargetSku', type: 'string', interface: 'input', uiSchema: { title: 'Target SKU' } },
    { name: 'familyTier', type: 'string', interface: 'input', uiSchema: { title: 'Family Tier' }, index: true },
    { name: 'familyTierScore', type: 'double', interface: 'number', uiSchema: { title: 'Family Tier Score' } },
    { name: 'familyCurrentPlanningStock', type: 'double', interface: 'number', uiSchema: { title: 'Family Stock' } },
    { name: 'familyOnHandStock', type: 'double', interface: 'number', uiSchema: { title: 'Family On Hand' } },
    {
      name: 'familyOnHandSellableStock',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Family On-Hand Sellable Stock' },
    },
    {
      name: 'familyAmazonPipelineStock',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Family Amazon Pipeline Stock' },
    },
    {
      name: 'familySupplierPipelineStock',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Family Supplier Pipeline Stock' },
    },
    {
      name: 'familyInventoryPositionStock',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Family Inventory Position Stock' },
    },
    {
      name: 'familyFuturePositionStock',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Family Future Position' },
    },
    { name: 'familySellableStock', type: 'double', interface: 'number', uiSchema: { title: 'Family Sellable' } },
    { name: 'familyReservedStock', type: 'double', interface: 'number', uiSchema: { title: 'Family Reserved' } },
    { name: 'familyPipelineStock', type: 'double', interface: 'number', uiSchema: { title: 'Family Pipeline' } },
    { name: 'familyInboundStock', type: 'double', interface: 'number', uiSchema: { title: 'Family Inbound' } },
    { name: 'familyOrderedStock', type: 'double', interface: 'number', uiSchema: { title: 'Family Ordered' } },
    { name: 'familyPrepStock', type: 'double', interface: 'number', uiSchema: { title: 'Family Prep' } },
    { name: 'familyAwdStock', type: 'double', interface: 'number', uiSchema: { title: 'Family AWD' } },
    { name: 'familySalesVelocity', type: 'double', interface: 'number', uiSchema: { title: 'Family Velocity' } },
    { name: 'familyDaysOfCover', type: 'double', interface: 'number', uiSchema: { title: 'Family Days of Cover' } },
    { name: 'familyEstimatedOosDate', type: 'dateOnly', interface: 'date', uiSchema: { title: 'Family OOS Date' } },
    {
      name: 'familyPositionDaysOfCover',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Family Position Days of Cover' },
    },
    {
      name: 'familyPositionEstimatedOosDate',
      type: 'dateOnly',
      interface: 'date',
      uiSchema: { title: 'Family Position OOS Date' },
    },
    {
      name: 'familyOpenOrderCoverageQty',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Family Order Coverage' },
    },
    {
      name: 'familyTrustedSupplierOrderCoverageQty',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Family Trusted Supplier Order Coverage' },
    },
    {
      name: 'familySuggestedReorderQty',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Family Suggested Qty' },
    },
    {
      name: 'familyPreferredSupplierId',
      type: 'uuid',
      autoFill: false,
      interface: 'input',
      uiSchema: { title: 'Family Supplier' },
    },
    {
      name: 'familyPreferredSupplierProductId',
      type: 'uuid',
      autoFill: false,
      interface: 'input',
      uiSchema: { title: 'Family Supplier Product' },
    },
    {
      name: 'familyPreferredSupplierName',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Family Supplier Name' },
    },
    { name: 'familyUnitCost', type: 'double', interface: 'number', uiSchema: { title: 'Family Unit Cost' } },
    { name: 'familyLeadTimeDays', type: 'double', interface: 'number', uiSchema: { title: 'Family Lead Time' } },
    { name: 'familyEstimatedOrderCost', type: 'double', interface: 'number', uiSchema: { title: 'Family Order Cost' } },
    {
      name: 'familyStuck',
      type: 'boolean',
      interface: 'checkbox',
      uiSchema: { title: 'Family Stuck' },
      defaultValue: false,
    },
    {
      name: 'familyStuckAction',
      type: 'boolean',
      interface: 'checkbox',
      uiSchema: { title: 'Family Stuck Action Row' },
      defaultValue: false,
    },
    {
      name: 'familyStuckClassification',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Family Stuck Reason' },
    },
    {
      name: 'familyStuckAffectedMemberCount',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Affected Members' },
    },
    { name: 'familyStuckAffectedUnits', type: 'double', interface: 'number', uiSchema: { title: 'Affected Units' } },
    { name: 'familyStuckAffectedValue', type: 'double', interface: 'number', uiSchema: { title: 'Affected Value' } },
    {
      name: 'familyStuckActiveOrderCount',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Active Orders' },
    },
    {
      name: 'familyStuckEvidence',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Family Stuck Evidence' },
      defaultValue: {},
    },
    {
      name: 'familyRollupEvidence',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Family Rollup Evidence' },
      defaultValue: {},
    },
    {
      name: 'refreshRun',
      type: 'belongsTo',
      target: ECOBASE_COLLECTIONS.goldInventoryPlanningRefreshRuns,
      foreignKey: 'refreshRunId',
      targetKey: 'id',
      onDelete: 'RESTRICT',
    },
    {
      name: 'calculationDate',
      type: 'dateOnly',
      interface: 'date',
      uiSchema: { title: 'Calculation Date' },
      allowNull: false,
      index: true,
    },
    { name: 'company', type: 'string', interface: 'input', uiSchema: { title: 'Company' }, index: true },
    { name: 'asin', type: 'string', interface: 'input', uiSchema: { title: 'ASIN' }, index: true },
    { name: 'sku', type: 'string', interface: 'input', uiSchema: { title: 'SKU' }, index: true },
    { name: 'title', type: 'text', interface: 'textarea', uiSchema: { title: 'Title' } },
    { name: 'brand', type: 'string', interface: 'input', uiSchema: { title: 'Brand' } },
    { name: 'productStatus', type: 'string', interface: 'input', uiSchema: { title: 'Product Status' }, index: true },
    {
      name: 'planningExcluded',
      type: 'boolean',
      interface: 'checkbox',
      uiSchema: { title: 'Planning Excluded' },
      defaultValue: false,
    },
    {
      name: 'actionStatus',
      type: 'string',
      interface: 'select',
      uiSchema: { title: 'Action Status', enum: ACTION_STATUS_OPTIONS },
      allowNull: false,
      index: true,
    },
    { name: 'tier', type: 'string', interface: 'select', uiSchema: { title: 'Tier', enum: TIER_OPTIONS }, index: true },
    { name: 'tierScore', type: 'double', interface: 'number', uiSchema: { title: 'Tier Score' } },
    { name: 'recentUnits30', type: 'double', interface: 'number', uiSchema: { title: 'Recent Units (30 Days)' } },
    {
      name: 'tierEligibilityReason',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Tier Eligibility Reason' },
      index: true,
    },
    {
      name: 'tierRuleVersion',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Tier Rule Version' },
      index: true,
    },
    {
      name: 'currentTier',
      type: 'string',
      interface: 'select',
      uiSchema: { title: 'Current Tier', enum: TIER_OPTIONS },
      index: true,
    },
    { name: 'currentTierScore', type: 'double', interface: 'number', uiSchema: { title: 'Current Tier Score' } },
    {
      name: 'averageTier',
      type: 'string',
      interface: 'select',
      uiSchema: { title: 'Average Tier', enum: TIER_OPTIONS },
      index: true,
    },
    { name: 'averageTierScore', type: 'double', interface: 'number', uiSchema: { title: 'Average Tier Score' } },
    {
      name: 'bestTier',
      type: 'string',
      interface: 'select',
      uiSchema: { title: 'Best Tier', enum: TIER_OPTIONS },
      index: true,
    },
    { name: 'bestTierScore', type: 'double', interface: 'number', uiSchema: { title: 'Best Tier Score' } },
    { name: 'lastMonthQty', type: 'double', interface: 'number', uiSchema: { title: 'Last Month Qty' } },
    { name: 'sixMonthAverageQty', type: 'double', interface: 'number', uiSchema: { title: 'Six-Month Average Qty' } },
    { name: 'sixMonthWorstQty', type: 'double', interface: 'number', uiSchema: { title: 'Six-Month Worst Qty' } },
    { name: 'sixMonthBestQty', type: 'double', interface: 'number', uiSchema: { title: 'Six-Month Best Qty' } },
    { name: 'sixMonthMargin', type: 'double', interface: 'number', uiSchema: { title: 'Six-Month Margin' } },
    {
      name: 'previousTier',
      type: 'string',
      interface: 'select',
      uiSchema: { title: 'Previous Tier', enum: TIER_OPTIONS },
      index: true,
    },
    { name: 'tierMovement', type: 'string', interface: 'input', uiSchema: { title: 'Tier Movement' }, index: true },
    { name: 'profitPerUnit', type: 'double', interface: 'number', uiSchema: { title: 'Profit Per Unit' } },
    { name: 'estimatedProfitRisk', type: 'double', interface: 'number', uiSchema: { title: 'Estimated Profit Risk' } },
    {
      name: 'estimatedProfitRiskBasis',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Estimated Profit Risk Basis' },
    },
    { name: 'moneyRiskStatus', type: 'string', interface: 'input', uiSchema: { title: 'Money Risk Status' } },
    {
      name: 'moneyRiskUncoveredDays',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Money Risk Uncovered Days' },
    },
    {
      name: 'moneyRiskInputs',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Money Risk Inputs' },
      defaultValue: {},
    },
    { name: 'unitCost', type: 'double', interface: 'number', uiSchema: { title: 'Unit Cost' } },
    { name: 'unitCostSource', type: 'string', interface: 'input', uiSchema: { title: 'Unit Cost Source' } },
    { name: 'supplierAvailability', type: 'string', interface: 'input', uiSchema: { title: 'Supplier Availability' } },
    { name: 'leadTimeAvailability', type: 'string', interface: 'input', uiSchema: { title: 'Lead-Time Availability' } },
    { name: 'unitCostAvailability', type: 'string', interface: 'input', uiSchema: { title: 'Unit Cost Availability' } },
    { name: 'profitAvailability', type: 'string', interface: 'input', uiSchema: { title: 'Profit Availability' } },
    { name: 'estimatedOrderCost', type: 'double', interface: 'number', uiSchema: { title: 'Estimated Order Cost' } },
    { name: 'recommendedBestQty', type: 'double', interface: 'number', uiSchema: { title: 'Recommended Best Qty' } },
    { name: 'salesVelocity', type: 'double', interface: 'number', uiSchema: { title: 'Sales Velocity' } },
    { name: 'salesVelocityBasis', type: 'string', interface: 'input', uiSchema: { title: 'Velocity Basis' } },
    { name: 'salesVelocityStatus', type: 'string', interface: 'input', uiSchema: { title: 'Velocity Status' } },
    {
      name: 'salesVelocityWindowStart',
      type: 'dateOnly',
      interface: 'date',
      uiSchema: { title: 'Velocity Window Start' },
    },
    { name: 'salesVelocityWindowEnd', type: 'dateOnly', interface: 'date', uiSchema: { title: 'Velocity Window End' } },
    { name: 'salesVelocityAsOfDate', type: 'dateOnly', interface: 'date', uiSchema: { title: 'Velocity As Of' } },
    { name: 'suggestedReorderQty', type: 'double', interface: 'number', uiSchema: { title: 'Suggested Reorder Qty' } },
    { name: 'safetyBufferDays', type: 'integer', interface: 'integer', uiSchema: { title: 'Safety Buffer Days' } },
    { name: 'reorderCycleDays', type: 'integer', interface: 'integer', uiSchema: { title: 'Reorder Cycle Days' } },
    { name: 'targetCoverDays', type: 'integer', interface: 'integer', uiSchema: { title: 'Target Cover Days' } },
    {
      name: 'orderSoonWindowDays',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Order-Soon Window Days' },
    },
    {
      name: 'leadTimeFreshnessDays',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Lead-Time Freshness Days' },
    },
    {
      name: 'purchasedPipelineGraceDays',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Purchased Pipeline Grace Days' },
    },
    {
      name: 'currentPlanningStock',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Current Planning Stock' },
    },
    { name: 'onHandStock', type: 'double', interface: 'number', uiSchema: { title: 'On-Hand Stock' } },
    {
      name: 'onHandSellableStock',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'On-Hand Sellable Stock' },
    },
    {
      name: 'amazonPipelineStock',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Amazon Pipeline Stock' },
    },
    {
      name: 'supplierPipelineStock',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Supplier Pipeline Stock' },
    },
    {
      name: 'inventoryPositionStock',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Inventory Position Stock' },
    },
    {
      name: 'futurePositionStock',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Future Position Stock' },
    },
    { name: 'sellableStock', type: 'double', interface: 'number', uiSchema: { title: 'Sellable Stock' } },
    { name: 'reservedStock', type: 'double', interface: 'number', uiSchema: { title: 'Reserved Stock' } },
    { name: 'pipelineStock', type: 'double', interface: 'number', uiSchema: { title: 'Replenishment Stock' } },
    { name: 'inboundStock', type: 'double', interface: 'number', uiSchema: { title: 'Inbound Stock' } },
    { name: 'orderedStock', type: 'double', interface: 'number', uiSchema: { title: 'Ordered Stock' } },
    { name: 'prepStock', type: 'double', interface: 'number', uiSchema: { title: 'Prep Stock' } },
    { name: 'awdStock', type: 'double', interface: 'number', uiSchema: { title: 'AWD Stock' } },
    {
      name: 'openOrderCoverageQty',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Open Order Coverage Qty' },
    },
    {
      name: 'trustedSupplierOrderCoverageQty',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Trusted Supplier Order Coverage Qty' },
    },
    {
      name: 'supplierOrderState',
      type: 'string',
      interface: 'select',
      uiSchema: { title: 'Supplier Order State', enum: SUPPLIER_ORDER_STATE_OPTIONS },
      index: true,
    },
    {
      name: 'supplierOrderStale',
      type: 'boolean',
      interface: 'checkbox',
      uiSchema: { title: 'Supplier Order Stale' },
      defaultValue: false,
      index: true,
    },
    {
      name: 'supplierOrderId',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Supplier Order ID' },
      index: true,
    },
    { name: 'supplierOrderStatus', type: 'string', interface: 'input', uiSchema: { title: 'Supplier Order Status' } },
    { name: 'supplierOrderRef', type: 'string', interface: 'input', uiSchema: { title: 'Supplier Order Ref' } },
    {
      name: 'supplierOrderAuthorityStatus',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Supplier Order Authority Status' },
    },
    {
      name: 'supplierOrderAuthoritySource',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Supplier Order Authority Source' },
    },
    {
      name: 'supplierOrderAuthorityTaskRef',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Supplier Order Authority Task Ref' },
    },
    {
      name: 'supplierOrderAuthorityAsOf',
      type: 'datetimeTz',
      interface: 'datetime',
      uiSchema: { title: 'Supplier Order Authority As Of' },
    },
    {
      name: 'supplierOrderAuthorityEvidence',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Supplier Order Authority Evidence' },
      defaultValue: {},
    },
    {
      name: 'amazonReceiptStatus',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Amazon Receipt Status' },
      index: true,
    },
    {
      name: 'amazonReceiptObservedAt',
      type: 'datetimeTz',
      interface: 'datetime',
      uiSchema: { title: 'Amazon Receipt Observed At' },
    },
    {
      name: 'amazonReceiptCompletionReason',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Amazon Receipt Completion Reason' },
    },
    {
      name: 'amazonReceiptEvidenceJson',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Amazon Receipt Evidence' },
      defaultValue: {},
    },
    {
      name: 'supplierOrderOpenQty',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Supplier Order Open Qty' },
    },
    {
      name: 'supplierOrderReferenceOpenQty',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Current Supplier Order Open Qty' },
    },
    {
      name: 'supplierOrderCycleSelection',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Supplier Order Cycle Selection' },
      defaultValue: {},
    },
    {
      name: 'supplierOrderCycleReviewRequired',
      type: 'boolean',
      interface: 'checkbox',
      uiSchema: { title: 'Supplier Order Cycle Review Required' },
      defaultValue: false,
      index: true,
    },
    {
      name: 'supplierOrderPurchasedOpenQty',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Purchased Open Qty' },
    },
    {
      name: 'supplierOrderPlacedNotPurchasedOpenQty',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Placed Not Purchased Open Qty' },
    },
    {
      name: 'pipelineHealthStatus',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Pipeline Health' },
      index: true,
    },
    { name: 'stockoutGapDays', type: 'double', interface: 'number', uiSchema: { title: 'Stockout Gap Days' } },
    {
      name: 'stuck',
      type: 'boolean',
      interface: 'checkbox',
      uiSchema: { title: 'Stuck Inventory' },
      defaultValue: false,
      index: true,
    },
    {
      name: 'stuckClassification',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Stuck Classification' },
      index: true,
    },
    {
      name: 'commandCenterPane',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Command Center Pane' },
      index: true,
    },
    {
      name: 'commandCenterPaneReason',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Command Center Pane Reason' },
    },
    {
      name: 'planningEligibilityStatus',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Planning Eligibility' },
      index: true,
    },
    {
      name: 'planningEligibilityReason',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Planning Eligibility Reason' },
    },
    { name: 'dataQualityStatus', type: 'string', interface: 'input', uiSchema: { title: 'Data Quality' }, index: true },
    {
      name: 'dataQualityIssues',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Data Quality Issues' },
      defaultValue: [],
    },
    {
      name: 'readinessDomains',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Readiness Domains' },
      defaultValue: {},
    },
    {
      name: 'readinessReasonCodes',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Readiness Reason Codes' },
      defaultValue: [],
    },
    {
      name: 'operationalIssues',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Operational Issues' },
      defaultValue: [],
    },
    { name: 'inventoryAsOfDate', type: 'dateOnly', interface: 'date', uiSchema: { title: 'Inventory As Of' } },
    {
      name: 'sourceFreshnessStatus',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Source Freshness' },
      index: true,
    },
    {
      name: 'latestSupplierOrderActivityType',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Latest Order Activity Type' },
    },
    {
      name: 'latestSupplierOrderActivityAt',
      type: 'datetimeTz',
      interface: 'datetime',
      uiSchema: { title: 'Latest Order Activity At' },
    },
    {
      name: 'latestSupplierOrderActivityNote',
      type: 'text',
      interface: 'textarea',
      uiSchema: { title: 'Latest Order Activity Note' },
    },
    {
      name: 'latestSupplierOrderActivityActor',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Latest Order Activity Actor' },
    },
    {
      name: 'latestSupplierOrderActivityActorUserId',
      type: 'bigInt',
      interface: 'integer',
      uiSchema: { title: 'Latest Order Activity Actor User' },
    },
    {
      name: 'latestSupplierOrderActivityActorDisplayName',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Latest Order Activity Actor Display Name' },
    },
    {
      name: 'latestSupplierOrderActivityActorEmail',
      type: 'string',
      interface: 'email',
      uiSchema: { title: 'Latest Order Activity Actor Email' },
    },
    {
      name: 'latestSupplierOrderActivitySource',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Latest Order Activity Source' },
    },
    {
      name: 'recommendedEscalation',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Recommended Escalation' },
    },
    { name: 'daysOfCover', type: 'double', interface: 'number', uiSchema: { title: 'Days Of Cover' } },
    {
      name: 'estimatedOosDate',
      type: 'dateOnly',
      interface: 'date',
      uiSchema: { title: 'Estimated OOS Date' },
      index: true,
    },
    {
      name: 'daysUntilOos',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Days Until OOS' },
    },
    {
      name: 'positionDaysOfCover',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Position Days of Cover' },
    },
    {
      name: 'positionEstimatedOosDate',
      type: 'dateOnly',
      interface: 'date',
      uiSchema: { title: 'Position OOS Date' },
    },
    {
      name: 'latestSafeReorderDate',
      type: 'dateOnly',
      interface: 'date',
      uiSchema: { title: 'Latest Safe Reorder Date' },
      index: true,
    },
    {
      name: 'daysUntilSafeReorder',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Days Until Safe Reorder' },
    },
    { name: 'supplierId', type: 'string', interface: 'input', uiSchema: { title: 'Supplier ID' } },
    { name: 'supplierName', type: 'string', interface: 'input', uiSchema: { title: 'Supplier Name' }, index: true },
    { name: 'supplierSource', type: 'string', interface: 'input', uiSchema: { title: 'Supplier Source' } },
    { name: 'supplierRole', type: 'string', interface: 'input', uiSchema: { title: 'Supplier Role' } },
    { name: 'supplierConfidence', type: 'string', interface: 'input', uiSchema: { title: 'Supplier Confidence' } },
    { name: 'leadTimeDays', type: 'double', interface: 'number', uiSchema: { title: 'Lead Time Days' } },
    {
      name: 'leadTimeConfirmedAt',
      type: 'datetimeTz',
      interface: 'datetime',
      uiSchema: { title: 'Lead Time Confirmed At' },
    },
    {
      name: 'leadTimeFreshness',
      type: 'string',
      interface: 'select',
      uiSchema: { title: 'Lead Time Freshness', enum: LEAD_TIME_FRESHNESS_OPTIONS },
      index: true,
    },
    { name: 'expectedArrivalDate', type: 'dateOnly', interface: 'date', uiSchema: { title: 'Expected Arrival Date' } },
    {
      name: 'expectedArrivalStatus',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Expected Arrival Status' },
    },
    {
      name: 'expectedArrivalSource',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Expected Arrival Source' },
    },
    { name: 'expectedArrivalAsOf', type: 'dateOnly', interface: 'date', uiSchema: { title: 'Expected Arrival As Of' } },
    {
      name: 'expectedArrivalConfidence',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Expected Arrival Confidence' },
    },
    {
      name: 'expectedArrivalFreshness',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Expected Arrival Freshness' },
    },
    {
      name: 'digestPriority',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Digest Priority' },
      index: true,
    },
    { name: 'evidence', type: 'jsonb', interface: 'json', uiSchema: { title: 'Evidence' }, defaultValue: {} },
    {
      name: 'lastRefreshedAt',
      type: 'datetimeTz',
      interface: 'datetime',
      uiSchema: { title: 'Last Refreshed At' },
      index: true,
    },
  ],
});
