import { defineCollection } from '@nocobase/database';
import { ECOBASE_COLLECTIONS } from './names';

export default defineCollection({
  migrationRules: ['schema-only'],
  loadedFromCollectionManager: true,
  autoGenId: false,
  name: ECOBASE_COLLECTIONS.goldManagementKpiDailyFacts,
  title: 'Gold management KPI daily facts',
  indexes: [
    { unique: true, fields: ['naturalKey'] },
    { fields: ['metricDate', 'companyScope'] },
    { fields: ['metricKey', 'companyScope', 'metricDate'] },
  ],
  fields: [
    { name: 'id', type: 'uuid', interface: 'input', uiSchema: { title: 'ID' }, primaryKey: true },
    {
      name: 'naturalKey',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Natural Key' },
      allowNull: false,
      unique: true,
    },
    {
      name: 'metricDate',
      type: 'dateOnly',
      interface: 'date',
      uiSchema: { title: 'Metric Date' },
      allowNull: false,
      index: true,
    },
    { name: 'company', type: 'string', interface: 'input', uiSchema: { title: 'Company' }, index: true },
    {
      name: 'companyScope',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Company Scope' },
      allowNull: false,
      index: true,
    },
    {
      name: 'metricKey',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Metric Key' },
      allowNull: false,
      index: true,
    },
    {
      name: 'metricLabel',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Metric Label' },
      allowNull: false,
    },
    { name: 'unit', type: 'string', interface: 'input', uiSchema: { title: 'Unit' }, allowNull: false },
    { name: 'value', type: 'double', interface: 'number', uiSchema: { title: 'Value' } },
    {
      name: 'aggregation',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Aggregation' },
      allowNull: false,
    },
    {
      name: 'higherIsBetter',
      type: 'boolean',
      interface: 'checkbox',
      uiSchema: { title: 'Higher Is Better' },
      allowNull: false,
      defaultValue: true,
    },
    {
      name: 'sourceLayer',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Source Layer' },
      allowNull: false,
    },
    {
      name: 'sourceCollection',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Source Collection' },
      allowNull: false,
    },
    {
      name: 'sourceDateStart',
      type: 'dateOnly',
      interface: 'date',
      uiSchema: { title: 'Source Date Start' },
      allowNull: false,
    },
    {
      name: 'sourceDateEnd',
      type: 'dateOnly',
      interface: 'date',
      uiSchema: { title: 'Source Date End' },
      allowNull: false,
    },
    {
      name: 'sourceRowCount',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Source Row Count' },
      allowNull: false,
      defaultValue: 0,
    },
    { name: 'sourceGoldDate', type: 'dateOnly', interface: 'date', uiSchema: { title: 'Source Gold Date' } },
    {
      name: 'metricVersion',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Metric Version' },
      allowNull: false,
    },
    {
      name: 'generatedAt',
      type: 'datetimeTz',
      interface: 'datetime',
      uiSchema: { title: 'Generated At' },
      allowNull: false,
    },
    { name: 'payload', type: 'jsonb', interface: 'json', uiSchema: { title: 'Payload' }, defaultValue: {} },
  ],
});
