import { defineCollection } from '@nocobase/database';
import { ECOBASE_COLLECTIONS } from './names';

export default defineCollection({
  migrationRules: ['schema-only'],
  loadedFromCollectionManager: true,
  autoGenId: false,
  name: ECOBASE_COLLECTIONS.goldOrderPlanningRows,
  title: 'Gold order planning rows',
  indexes: [{ unique: true, fields: ['orderId'] }],
  fields: [
    { name: 'id', type: 'uuid', interface: 'input', uiSchema: { title: 'ID' }, primaryKey: true },
    {
      name: 'order',
      type: 'belongsTo',
      target: ECOBASE_COLLECTIONS.silverOrders,
      foreignKey: 'orderId',
      targetKey: 'id',
      onDelete: 'CASCADE',
    },
    { name: 'orderRef', type: 'string', interface: 'input', uiSchema: { title: 'Order Ref' }, index: true },
    { name: 'companyId', type: 'uuid', interface: 'input', uiSchema: { title: 'Company ID' }, index: true },
    { name: 'companyName', type: 'string', interface: 'input', uiSchema: { title: 'Company' }, index: true },
    { name: 'supplierId', type: 'uuid', interface: 'input', uiSchema: { title: 'Supplier ID' }, index: true },
    { name: 'supplierName', type: 'string', interface: 'input', uiSchema: { title: 'Supplier' }, index: true },
    { name: 'lifecyclePhase', type: 'string', interface: 'input', uiSchema: { title: 'Lifecycle Phase' } },
    { name: 'lifecycleStatus', type: 'string', interface: 'input', uiSchema: { title: 'Lifecycle Status' } },
    {
      name: 'canonicalStatus',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Canonical Status' },
      index: true,
    },
    { name: 'currentStatus', type: 'string', interface: 'input', uiSchema: { title: 'Current Status' }, index: true },
    { name: 'statusSource', type: 'string', interface: 'input', uiSchema: { title: 'Status Source' } },
    {
      name: 'statusCheckRequired',
      type: 'boolean',
      interface: 'checkbox',
      uiSchema: { title: 'Needs Status Check' },
      defaultValue: false,
      index: true,
    },
    {
      name: 'statusEvidenceJson',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Status Evidence' },
      defaultValue: {},
    },
    { name: 'tier', type: 'string', interface: 'input', uiSchema: { title: 'Tier' }, index: true },
    { name: 'tierRank', type: 'integer', interface: 'integer', uiSchema: { title: 'Tier Rank' } },
    { name: 'nextAction', type: 'string', interface: 'input', uiSchema: { title: 'Next Action' } },
    { name: 'nextActionDueAt', type: 'datetimeTz', interface: 'datetime', uiSchema: { title: 'Next Action Due' } },
    { name: 'expectedDeliveryDate', type: 'dateOnly', interface: 'date', uiSchema: { title: 'Expected Delivery' } },
    { name: 'trackingId', type: 'string', interface: 'input', uiSchema: { title: 'Tracking ID' } },
    { name: 'asinCount', type: 'integer', interface: 'integer', uiSchema: { title: 'ASIN Count' } },
    { name: 'lineCount', type: 'integer', interface: 'integer', uiSchema: { title: 'Line Count' } },
    { name: 'moneyAtRisk', type: 'double', interface: 'number', uiSchema: { title: 'Money At Risk' }, index: true },
    { name: 'riskSource', type: 'string', interface: 'input', uiSchema: { title: 'Risk Source' } },
    { name: 'earliestOosDate', type: 'dateOnly', interface: 'date', uiSchema: { title: 'Earliest OOS' }, index: true },
    { name: 'daysUntilOos', type: 'integer', interface: 'integer', uiSchema: { title: 'Days Until OOS' } },
    { name: 'daysSinceLastActivity', type: 'integer', interface: 'integer', uiSchema: { title: 'Waiting Days' } },
    { name: 'latestComment', type: 'text', interface: 'textarea', uiSchema: { title: 'Latest Comment' } },
    { name: 'remarks', type: 'text', interface: 'textarea', uiSchema: { title: 'Remarks' } },
    { name: 'searchText', type: 'text', interface: 'textarea', uiSchema: { title: 'Search Text' } },
    {
      name: 'latestGoldCalculationDate',
      type: 'dateOnly',
      interface: 'date',
      uiSchema: { title: 'Latest Gold Calculation' },
    },
    {
      name: 'lastRefreshedAt',
      type: 'datetimeTz',
      interface: 'datetime',
      uiSchema: { title: 'Last Refreshed At' },
      index: true,
    },
  ],
});
