/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */

import { defineCollection } from '@nocobase/database';
import { ECOBASE_COLLECTIONS } from './names';

const ACTION_STATUS_OPTIONS = [
  { label: 'Overdue', value: 'overdue', color: 'red' },
  { label: 'Order today', value: 'order_today', color: 'volcano' },
  { label: 'Order soon', value: 'order_soon', color: 'orange' },
  { label: 'Missing lead time', value: 'missing_lead_time', color: 'gold' },
  { label: 'Stale lead time', value: 'stale_lead_time', color: 'orange' },
  { label: 'Already ordered', value: 'already_ordered', color: 'blue' },
  { label: 'Watch', value: 'watch', color: 'cyan' },
  { label: 'Sufficient stock', value: 'sufficient_stock', color: 'green' },
  { label: 'No sell-through', value: 'no_sell_through', color: 'purple' },
  { label: 'Excluded', value: 'excluded', color: 'default' },
];

const LEAD_TIME_FRESHNESS_OPTIONS = [
  { label: 'Fresh', value: 'fresh', color: 'green' },
  { label: 'Default (30 days)', value: 'default', color: 'blue' },
  { label: 'Stale', value: 'stale', color: 'orange' },
  { label: 'Missing', value: 'missing', color: 'red' },
];

const SUPPLIER_ORDER_STATE_OPTIONS = [
  { label: 'No order history', value: 'no_open_order', color: 'red' },
  { label: 'No open order', value: 'closed_history', color: 'default' },
  { label: 'Order placed, not purchased', value: 'placed_not_purchased', color: 'orange' },
  { label: 'Purchased / pipeline', value: 'purchased_pipeline', color: 'blue' },
];

export default defineCollection({
  migrationRules: ['schema-only'],
  loadedFromCollectionManager: true,
  hidden: true,
  autoGenId: false,
  name: ECOBASE_COLLECTIONS.goldInventoryPlanningRows,
  title: 'Gold inventory planning rows',
  fields: [
    { name: 'id', type: 'uuid', interface: 'input', uiSchema: { title: 'ID' }, primaryKey: true },
    {
      name: 'naturalKey',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Natural Key' },
      allowNull: false,
      unique: true,
    },
    {
      name: 'companyProduct',
      type: 'belongsTo',
      target: ECOBASE_COLLECTIONS.silverCompanyProducts,
      foreignKey: 'companyProductId',
      targetKey: 'id',
      onDelete: 'CASCADE',
    },
    {
      name: 'companyProductFamily',
      type: 'belongsTo',
      target: ECOBASE_COLLECTIONS.silverCompanyProductFamilies,
      foreignKey: 'companyProductFamilyId',
      targetKey: 'id',
      onDelete: 'SET NULL',
    },
    {
      name: 'refreshRun',
      type: 'belongsTo',
      target: ECOBASE_COLLECTIONS.goldInventoryPlanningRefreshRuns,
      foreignKey: 'refreshRunId',
      targetKey: 'id',
      onDelete: 'RESTRICT',
    },
    { name: 'companyId', type: 'uuid', interface: 'input', autoFill: false, index: true },
    { name: 'amazonAccountId', type: 'uuid', interface: 'input', autoFill: false, index: true },
    { name: 'marketplace', type: 'string', interface: 'input', index: true },
    { name: 'ruleVersion', type: 'string', interface: 'input', index: true },
    { name: 'algorithmContractVersion', type: 'string', interface: 'input' },
    { name: 'currentProjectionGateMode', type: 'string', interface: 'input' },
    { name: 'resolvedPlanningSettingsDigest', type: 'string', interface: 'input' },
    { name: 'sourceCoverageDigest', type: 'string', interface: 'input' },
    { name: 'sourceInputDigest', type: 'string', interface: 'input' },
    { name: 'protectedSilverFingerprint', type: 'string', interface: 'input' },
    { name: 'candidateInputDigest', type: 'string', interface: 'input' },
    { name: 'productCoverageDigest', type: 'string', interface: 'input' },
    { name: 'sourceAsOfDate', type: 'dateOnly', interface: 'date' },
    { name: 'baselineWindowStartDate', type: 'dateOnly', interface: 'date' },
    { name: 'baselineWindowEndDate', type: 'dateOnly', interface: 'date' },
    { name: 'baselineEligibleMonthCount', type: 'integer', interface: 'integer' },
    { name: 'baselineConfidence', type: 'string', interface: 'input', index: true },
    { name: 'monthlyPerformanceEvidence', type: 'jsonb', interface: 'json' },
    {
      name: 'baselineTotalUnits',
      type: 'decimal',
      precision: 30,
      scale: 8,
      interface: 'number',
    },
    {
      name: 'baselineTotalProfit',
      type: 'decimal',
      precision: 30,
      scale: 8,
      interface: 'number',
    },
    {
      name: 'baselineWeightedProfitPerUnit',
      type: 'decimal',
      precision: 30,
      scale: 8,
      interface: 'number',
    },
    {
      name: 'averageMonthlyUnits',
      type: 'decimal',
      precision: 30,
      scale: 8,
      interface: 'number',
    },
    {
      name: 'averageMonthlyProfit',
      type: 'decimal',
      precision: 30,
      scale: 8,
      interface: 'number',
    },
    { name: 'baselineTierScore', type: 'decimal', precision: 30, scale: 8, interface: 'number' },
    { name: 'baselineTier', type: 'string', interface: 'input', index: true },
    { name: 'baselineState', type: 'string', interface: 'input', index: true },
    { name: 'baselineReasonCodes', type: 'jsonb', interface: 'json' },
    { name: 'bestMonthlyUnits', type: 'decimal', precision: 30, scale: 8, interface: 'number' },
    { name: 'bestUnitsMonth', type: 'dateOnly', interface: 'date' },
    { name: 'bestMonthlyProfit', type: 'decimal', precision: 30, scale: 8, interface: 'number' },
    { name: 'bestProfitMonth', type: 'dateOnly', interface: 'date' },
    { name: 'worstMonthlyUnits', type: 'decimal', precision: 30, scale: 8, interface: 'number' },
    { name: 'worstUnitsMonth', type: 'dateOnly', interface: 'date' },
    { name: 'worstMonthlyProfit', type: 'decimal', precision: 30, scale: 8, interface: 'number' },
    { name: 'worstProfitMonth', type: 'dateOnly', interface: 'date' },
    { name: 'lastClosedMonth', type: 'dateOnly', interface: 'date' },
    { name: 'lastClosedMonthUnits', type: 'decimal', precision: 30, scale: 8, interface: 'number' },
    { name: 'lastClosedMonthProfit', type: 'decimal', precision: 30, scale: 8, interface: 'number' },
    {
      name: 'lastClosedMonthTierScore',
      type: 'decimal',
      precision: 30,
      scale: 8,
      interface: 'number',
    },
    { name: 'lastClosedMonthTier', type: 'string', interface: 'input', index: true },
    { name: 'lastClosedMonthState', type: 'string', interface: 'input', index: true },
    { name: 'lastClosedMonthReasonCodes', type: 'jsonb', interface: 'json' },
    { name: 'currentMonthStartDate', type: 'dateOnly', interface: 'date' },
    { name: 'currentCoverageEndDate', type: 'dateOnly', interface: 'date' },
    { name: 'currentCoveredDays', type: 'integer', interface: 'integer' },
    { name: 'currentMonthUnits', type: 'decimal', precision: 30, scale: 8, interface: 'number' },
    { name: 'currentMonthProfit', type: 'decimal', precision: 30, scale: 8, interface: 'number' },
    { name: 'projectedMonthlyUnits', type: 'decimal', precision: 30, scale: 8, interface: 'number' },
    { name: 'projectedMonthlyProfit', type: 'decimal', precision: 30, scale: 8, interface: 'number' },
    {
      name: 'currentProjectedTierScore',
      type: 'decimal',
      precision: 30,
      scale: 8,
      interface: 'number',
    },
    { name: 'currentProjectedTier', type: 'string', interface: 'input', index: true },
    { name: 'currentProjectedState', type: 'string', interface: 'input', index: true },
    { name: 'currentProjectionConfidence', type: 'string', interface: 'input', index: true },
    { name: 'currentProjectionReasonCodes', type: 'jsonb', interface: 'json' },
    { name: 'closedTierMovement', type: 'string', interface: 'input', index: true },
    { name: 'projectedTierMovement', type: 'string', interface: 'input', index: true },
    { name: 'trendReasonCodes', type: 'jsonb', interface: 'json' },
    {
      name: 'expectedAverageUnitsMtd',
      type: 'decimal',
      precision: 30,
      scale: 8,
      interface: 'number',
    },
    { name: 'expectedBestUnitsMtd', type: 'decimal', precision: 30, scale: 8, interface: 'number' },
    { name: 'expectedWorstUnitsMtd', type: 'decimal', precision: 30, scale: 8, interface: 'number' },
    {
      name: 'expectedAverageProfitMtd',
      type: 'decimal',
      precision: 30,
      scale: 8,
      interface: 'number',
    },
    { name: 'expectedBestProfitMtd', type: 'decimal', precision: 30, scale: 8, interface: 'number' },
    { name: 'expectedWorstProfitMtd', type: 'decimal', precision: 30, scale: 8, interface: 'number' },
    { name: 'quantityPaceStatus', type: 'string', interface: 'input', index: true },
    { name: 'profitPaceStatus', type: 'string', interface: 'input', index: true },
    { name: 'aggregatePaceStatus', type: 'string', interface: 'input', index: true },
    { name: 'paceCause', type: 'string', interface: 'input' },
    { name: 'paceEvidence', type: 'jsonb', interface: 'json' },
    { name: 'rollingUnits30', type: 'decimal', precision: 30, scale: 8, interface: 'number' },
    { name: 'rollingVelocityWindowStartDate', type: 'dateOnly', interface: 'date' },
    { name: 'rollingVelocityWindowEndDate', type: 'dateOnly', interface: 'date' },
    { name: 'rollingVelocityEvidenceStatus', type: 'string', interface: 'input', index: true },
    { name: 'inventoryDisposition', type: 'string', interface: 'input', index: true },
    { name: 'inventoryDispositionReasonCode', type: 'string', interface: 'input' },
    { name: 'replenishmentEligibility', type: 'string', interface: 'input', index: true },
    { name: 'replenishmentBlockReasonCode', type: 'string', interface: 'input' },
    { name: 'newReplenishmentActionable', type: 'boolean', interface: 'checkbox', index: true },
    { name: 'oosAlertActionable', type: 'boolean', interface: 'checkbox', index: true },
    { name: 'supplyActionable', type: 'boolean', interface: 'checkbox', index: true },
    { name: 'recommendedOrderQty', type: 'decimal', precision: 30, scale: 8, interface: 'number' },
    { name: 'existingOrderFollowUp', type: 'boolean', interface: 'checkbox', index: true },
    { name: 'existingOrderFollowUpAction', type: 'string', interface: 'input' },
    { name: 'primaryActionPane', type: 'string', interface: 'input', index: true },
    { name: 'primaryActionReasonCode', type: 'string', interface: 'input' },
    { name: 'isFrozenFamilyTarget', type: 'boolean', interface: 'checkbox', index: true },
    { name: 'familyTargetCompanyProductId', type: 'uuid', interface: 'input', autoFill: false, index: true },
    { name: 'listingReviewCategories', type: 'jsonb', interface: 'json' },
    { name: 'calculationEvidence', type: 'jsonb', interface: 'json' },
    {
      name: 'calculationDate',
      type: 'dateOnly',
      interface: 'date',
      uiSchema: { title: 'Calculation Date' },
      allowNull: false,
      index: true,
    },
    { name: 'company', type: 'string', interface: 'input', uiSchema: { title: 'Company' }, index: true },
    { name: 'asin', type: 'string', interface: 'input', uiSchema: { title: 'ASIN' }, index: true },
    { name: 'sku', type: 'string', interface: 'input', uiSchema: { title: 'SKU' }, index: true },
    { name: 'title', type: 'text', interface: 'textarea', uiSchema: { title: 'Title' } },
    { name: 'brand', type: 'string', interface: 'input', uiSchema: { title: 'Brand' } },
    { name: 'productStatus', type: 'string', interface: 'input', uiSchema: { title: 'Product Status' }, index: true },
    {
      name: 'planningExcluded',
      type: 'boolean',
      interface: 'checkbox',
      uiSchema: { title: 'Planning Excluded' },
      defaultValue: false,
    },
    {
      name: 'actionStatus',
      type: 'string',
      interface: 'select',
      uiSchema: { title: 'Action Status', enum: ACTION_STATUS_OPTIONS },
      allowNull: false,
      index: true,
    },
    { name: 'estimatedProfitRisk', type: 'double', interface: 'number', uiSchema: { title: 'Estimated Profit Risk' } },
    {
      name: 'estimatedProfitRiskBasis',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Estimated Profit Risk Basis' },
    },
    { name: 'moneyRiskStatus', type: 'string', interface: 'input', uiSchema: { title: 'Money Risk Status' } },
    {
      name: 'moneyRiskUncoveredDays',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Money Risk Uncovered Days' },
    },
    {
      name: 'moneyRiskInputs',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Money Risk Inputs' },
      defaultValue: {},
    },
    { name: 'unitCost', type: 'double', interface: 'number', uiSchema: { title: 'Unit Cost' } },
    { name: 'unitCostSource', type: 'string', interface: 'input', uiSchema: { title: 'Unit Cost Source' } },
    { name: 'supplierAvailability', type: 'string', interface: 'input', uiSchema: { title: 'Supplier Availability' } },
    { name: 'leadTimeAvailability', type: 'string', interface: 'input', uiSchema: { title: 'Lead-Time Availability' } },
    { name: 'unitCostAvailability', type: 'string', interface: 'input', uiSchema: { title: 'Unit Cost Availability' } },
    { name: 'profitAvailability', type: 'string', interface: 'input', uiSchema: { title: 'Profit Availability' } },
    { name: 'estimatedOrderCost', type: 'double', interface: 'number', uiSchema: { title: 'Estimated Order Cost' } },
    { name: 'salesVelocity', type: 'double', interface: 'number', uiSchema: { title: 'Sales Velocity' } },
    { name: 'salesVelocityBasis', type: 'string', interface: 'input', uiSchema: { title: 'Velocity Basis' } },
    { name: 'salesVelocityStatus', type: 'string', interface: 'input', uiSchema: { title: 'Velocity Status' } },
    {
      name: 'salesVelocityWindowStart',
      type: 'dateOnly',
      interface: 'date',
      uiSchema: { title: 'Velocity Window Start' },
    },
    { name: 'salesVelocityWindowEnd', type: 'dateOnly', interface: 'date', uiSchema: { title: 'Velocity Window End' } },
    { name: 'salesVelocityAsOfDate', type: 'dateOnly', interface: 'date', uiSchema: { title: 'Velocity As Of' } },
    { name: 'safetyBufferDays', type: 'integer', interface: 'integer', uiSchema: { title: 'Safety Buffer Days' } },
    { name: 'reorderCycleDays', type: 'integer', interface: 'integer', uiSchema: { title: 'Reorder Cycle Days' } },
    { name: 'targetCoverDays', type: 'integer', interface: 'integer', uiSchema: { title: 'Target Cover Days' } },
    {
      name: 'orderSoonWindowDays',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Order-Soon Window Days' },
    },
    {
      name: 'leadTimeFreshnessDays',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Lead-Time Freshness Days' },
    },
    {
      name: 'purchasedPipelineGraceDays',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Purchased Pipeline Grace Days' },
    },
    {
      name: 'currentPlanningStock',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Current Planning Stock' },
    },
    { name: 'onHandStock', type: 'double', interface: 'number', uiSchema: { title: 'On-Hand Stock' } },
    {
      name: 'onHandSellableStock',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'On-Hand Sellable Stock' },
    },
    {
      name: 'amazonPipelineStock',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Amazon Pipeline Stock' },
    },
    {
      name: 'supplierPipelineStock',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Supplier Pipeline Stock' },
    },
    {
      name: 'inventoryPositionStock',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Inventory Position Stock' },
    },
    {
      name: 'futurePositionStock',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Future Position Stock' },
    },
    { name: 'sellableStock', type: 'double', interface: 'number', uiSchema: { title: 'Sellable Stock' } },
    { name: 'reservedStock', type: 'double', interface: 'number', uiSchema: { title: 'Reserved Stock' } },
    { name: 'pipelineStock', type: 'double', interface: 'number', uiSchema: { title: 'Replenishment Stock' } },
    { name: 'inboundStock', type: 'double', interface: 'number', uiSchema: { title: 'Inbound Stock' } },
    { name: 'orderedStock', type: 'double', interface: 'number', uiSchema: { title: 'Ordered Stock' } },
    { name: 'prepStock', type: 'double', interface: 'number', uiSchema: { title: 'Prep Stock' } },
    { name: 'awdStock', type: 'double', interface: 'number', uiSchema: { title: 'AWD Stock' } },
    {
      name: 'openOrderCoverageQty',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Open Order Coverage Qty' },
    },
    {
      name: 'trustedSupplierOrderCoverageQty',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Trusted Supplier Order Coverage Qty' },
    },
    {
      name: 'supplierOrderState',
      type: 'string',
      interface: 'select',
      uiSchema: { title: 'Supplier Order State', enum: SUPPLIER_ORDER_STATE_OPTIONS },
      index: true,
    },
    {
      name: 'supplierOrderStale',
      type: 'boolean',
      interface: 'checkbox',
      uiSchema: { title: 'Supplier Order Stale' },
      defaultValue: false,
      index: true,
    },
    {
      name: 'supplierOrderId',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Supplier Order ID' },
      index: true,
    },
    { name: 'supplierOrderStatus', type: 'string', interface: 'input', uiSchema: { title: 'Supplier Order Status' } },
    {
      name: 'supplierOrderOperationalStatus',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Supplier Order Operational Status' },
    },
    {
      name: 'supplierOrderWorkflowStage',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Supplier Order Workflow Stage' },
      index: true,
    },
    {
      name: 'supplierOrderSourceMemberSku',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Supplier Order Source Member SKU' },
    },
    {
      name: 'supplierOrderLineMappingScope',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Supplier Order Line Mapping Scope' },
      index: true,
    },
    { name: 'supplierOrderRef', type: 'string', interface: 'input', uiSchema: { title: 'Supplier Order Ref' } },
    {
      name: 'supplierOrderAuthorityStatus',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Supplier Order Authority Status' },
    },
    {
      name: 'supplierOrderAuthoritySource',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Supplier Order Authority Source' },
    },
    {
      name: 'supplierOrderAuthorityTaskRef',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Supplier Order Authority Task Ref' },
    },
    {
      name: 'supplierOrderAuthorityAsOf',
      type: 'datetimeTz',
      interface: 'datetime',
      uiSchema: { title: 'Supplier Order Authority As Of' },
    },
    {
      name: 'supplierOrderAuthorityEvidence',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Supplier Order Authority Evidence' },
      defaultValue: {},
    },
    {
      name: 'amazonReceiptStatus',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Amazon Receipt Status' },
      index: true,
    },
    {
      name: 'amazonReceiptObservedAt',
      type: 'datetimeTz',
      interface: 'datetime',
      uiSchema: { title: 'Amazon Receipt Observed At' },
    },
    {
      name: 'amazonReceiptCompletionReason',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Amazon Receipt Completion Reason' },
    },
    {
      name: 'amazonReceiptEvidenceJson',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Amazon Receipt Evidence' },
      defaultValue: {},
    },
    {
      name: 'supplierOrderOpenQty',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Supplier Order Open Qty' },
    },
    {
      name: 'supplierOrderReferenceOpenQty',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Current Supplier Order Open Qty' },
    },
    {
      name: 'supplierOrderCycleSelection',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Supplier Order Cycle Selection' },
      defaultValue: {},
    },
    {
      name: 'supplierOrderCycleReviewRequired',
      type: 'boolean',
      interface: 'checkbox',
      uiSchema: { title: 'Supplier Order Cycle Review Required' },
      defaultValue: false,
      index: true,
    },
    {
      name: 'supplierOrderPurchasedOpenQty',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Purchased Open Qty' },
    },
    {
      name: 'supplierOrderPlacedNotPurchasedOpenQty',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Placed Not Purchased Open Qty' },
    },
    {
      name: 'pipelineHealthStatus',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Pipeline Health' },
      index: true,
    },
    { name: 'stockoutGapDays', type: 'double', interface: 'number', uiSchema: { title: 'Stockout Gap Days' } },
    { name: 'dataQualityStatus', type: 'string', interface: 'input', uiSchema: { title: 'Data Quality' }, index: true },
    {
      name: 'dataQualityIssues',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Data Quality Issues' },
      defaultValue: [],
    },
    {
      name: 'readinessDomains',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Readiness Domains' },
      defaultValue: {},
    },
    {
      name: 'readinessReasonCodes',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Readiness Reason Codes' },
      defaultValue: [],
    },
    {
      name: 'operationalIssues',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Operational Issues' },
      defaultValue: [],
    },
    { name: 'inventoryAsOfDate', type: 'dateOnly', interface: 'date', uiSchema: { title: 'Inventory As Of' } },
    {
      name: 'sourceFreshnessStatus',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Source Freshness' },
      index: true,
    },
    {
      name: 'latestSupplierOrderActivityType',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Latest Order Activity Type' },
    },
    {
      name: 'latestSupplierOrderActivityAt',
      type: 'datetimeTz',
      interface: 'datetime',
      uiSchema: { title: 'Latest Order Activity At' },
    },
    {
      name: 'latestSupplierOrderActivityNote',
      type: 'text',
      interface: 'textarea',
      uiSchema: { title: 'Latest Order Activity Note' },
    },
    {
      name: 'latestSupplierOrderActivityActor',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Latest Order Activity Actor' },
    },
    {
      name: 'latestSupplierOrderActivityActorUserId',
      type: 'bigInt',
      interface: 'integer',
      uiSchema: { title: 'Latest Order Activity Actor User' },
    },
    {
      name: 'latestSupplierOrderActivityActorDisplayName',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Latest Order Activity Actor Display Name' },
    },
    {
      name: 'latestSupplierOrderActivityActorEmail',
      type: 'string',
      interface: 'email',
      uiSchema: { title: 'Latest Order Activity Actor Email' },
    },
    {
      name: 'latestSupplierOrderActivitySource',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Latest Order Activity Source' },
    },
    {
      name: 'recommendedEscalation',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Recommended Escalation' },
    },
    { name: 'daysOfCover', type: 'double', interface: 'number', uiSchema: { title: 'Days Of Cover' } },
    {
      name: 'estimatedOosDate',
      type: 'dateOnly',
      interface: 'date',
      uiSchema: { title: 'Estimated OOS Date' },
      index: true,
    },
    {
      name: 'daysUntilOos',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Days Until OOS' },
    },
    {
      name: 'positionDaysOfCover',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Position Days of Cover' },
    },
    {
      name: 'positionEstimatedOosDate',
      type: 'dateOnly',
      interface: 'date',
      uiSchema: { title: 'Position OOS Date' },
    },
    {
      name: 'latestSafeReorderDate',
      type: 'dateOnly',
      interface: 'date',
      uiSchema: { title: 'Latest Safe Reorder Date' },
      index: true,
    },
    {
      name: 'daysUntilSafeReorder',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Days Until Safe Reorder' },
    },
    { name: 'supplierId', type: 'string', interface: 'input', uiSchema: { title: 'Supplier ID' } },
    { name: 'supplierName', type: 'string', interface: 'input', uiSchema: { title: 'Supplier Name' }, index: true },
    { name: 'supplierSource', type: 'string', interface: 'input', uiSchema: { title: 'Supplier Source' } },
    { name: 'supplierRole', type: 'string', interface: 'input', uiSchema: { title: 'Supplier Role' } },
    { name: 'supplierConfidence', type: 'string', interface: 'input', uiSchema: { title: 'Supplier Confidence' } },
    { name: 'leadTimeDays', type: 'double', interface: 'number', uiSchema: { title: 'Lead Time Days' } },
    {
      name: 'leadTimeConfirmedAt',
      type: 'datetimeTz',
      interface: 'datetime',
      uiSchema: { title: 'Lead Time Confirmed At' },
    },
    {
      name: 'leadTimeFreshness',
      type: 'string',
      interface: 'select',
      uiSchema: { title: 'Lead Time Freshness', enum: LEAD_TIME_FRESHNESS_OPTIONS },
      index: true,
    },
    { name: 'expectedArrivalDate', type: 'dateOnly', interface: 'date', uiSchema: { title: 'Expected Arrival Date' } },
    {
      name: 'expectedArrivalStatus',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Expected Arrival Status' },
    },
    {
      name: 'expectedArrivalSource',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Expected Arrival Source' },
    },
    { name: 'expectedArrivalAsOf', type: 'dateOnly', interface: 'date', uiSchema: { title: 'Expected Arrival As Of' } },
    {
      name: 'expectedArrivalConfidence',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Expected Arrival Confidence' },
    },
    {
      name: 'expectedArrivalFreshness',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Expected Arrival Freshness' },
    },
    {
      name: 'digestPriority',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Digest Priority' },
      index: true,
    },
    {
      name: 'calculationProvenanceJson',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Calculation Provenance' },
    },
    { name: 'evidence', type: 'jsonb', interface: 'json', uiSchema: { title: 'Evidence' }, defaultValue: {} },
    {
      name: 'lastRefreshedAt',
      type: 'datetimeTz',
      interface: 'datetime',
      uiSchema: { title: 'Last Refreshed At' },
      index: true,
    },
  ],
});
