import { defineCollection } from '@nocobase/database';
import { ECOBASE_COLLECTIONS } from './names';

export default defineCollection({
  migrationRules: ['schema-only'],
  autoGenId: false,
  name: ECOBASE_COLLECTIONS.importRuns,
  title: 'Ecobase import runs',
  fields: [
    { name: 'id', type: 'uuid', interface: 'input', uiSchema: { title: 'ID' }, primaryKey: true },
    {
      name: 'sourceConnection',
      type: 'belongsTo',
      target: ECOBASE_COLLECTIONS.sourceConnections,
      foreignKey: 'sourceConnectionId',
      targetKey: 'id',
      allowNull: false,
      onDelete: 'CASCADE',
    },
    {
      name: 'adapterName',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Adapter Name' },
      allowNull: false,
      index: true,
    },
    {
      name: 'sourceIdentifier',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Source Identifier' },
      allowNull: false,
    },
    {
      name: 'sourceVersion',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Source Version' },
      allowNull: false,
    },
    {
      name: 'idempotencyKey',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Idempotency Key' },
      allowNull: false,
      unique: true,
    },
    {
      name: 'startedAt',
      type: 'datetimeTz',
      interface: 'datetime',
      uiSchema: { title: 'Started At' },
      allowNull: false,
    },
    { name: 'finishedAt', type: 'datetimeTz', interface: 'datetime', uiSchema: { title: 'Finished At' } },
    {
      name: 'status',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Status' },
      allowNull: false,
      defaultValue: 'pending',
      index: true,
    },
    {
      name: 'rowCount',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Row Count' },
      allowNull: false,
      defaultValue: 0,
    },
    {
      name: 'normalizedCount',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Normalized Count' },
      allowNull: false,
      defaultValue: 0,
    },
    {
      name: 'warningCount',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Warning Count' },
      allowNull: false,
      defaultValue: 0,
    },
    {
      name: 'errorCount',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Error Count' },
      allowNull: false,
      defaultValue: 0,
    },
    { name: 'errorMessage', type: 'text', interface: 'textarea', uiSchema: { title: 'Error Message' } },
    { name: 'summary', type: 'jsonb', interface: 'json', uiSchema: { title: 'Summary' }, defaultValue: {} },
    {
      name: 'rawImportRows',
      type: 'hasMany',
      target: ECOBASE_COLLECTIONS.rawImportRows,
      foreignKey: 'importRunId',
      onDelete: 'CASCADE',
    },
  ],
});
