import { defineCollection } from '@nocobase/database';
import { ECOBASE_COLLECTIONS } from './names';

const ACTION_STATUS_OPTIONS = [
  { label: 'Overdue', value: 'overdue', color: 'red' },
  { label: 'Order today', value: 'order_today', color: 'volcano' },
  { label: 'Order soon', value: 'order_soon', color: 'orange' },
  { label: 'Missing lead time', value: 'missing_lead_time', color: 'gold' },
  { label: 'Already ordered', value: 'already_ordered', color: 'blue' },
  { label: 'Watch', value: 'watch', color: 'cyan' },
  { label: 'Sufficient stock', value: 'sufficient_stock', color: 'green' },
  { label: 'Excluded', value: 'excluded', color: 'default' },
];

const TIER_OPTIONS = [
  { label: 'A', value: 'A', color: 'red' },
  { label: 'B', value: 'B', color: 'orange' },
  { label: 'C', value: 'C', color: 'blue' },
  { label: 'Unclassified', value: 'unclassified', color: 'default' },
];

const LEAD_TIME_FRESHNESS_OPTIONS = [
  { label: 'Fresh', value: 'fresh', color: 'green' },
  { label: 'Stale', value: 'stale', color: 'orange' },
  { label: 'Missing', value: 'missing', color: 'red' },
];

export default defineCollection({
  migrationRules: ['schema-only'],
  loadedFromCollectionManager: true,
  autoGenId: false,
  name: ECOBASE_COLLECTIONS.inventoryPlanningRows,
  title: 'Ecobase inventory planning rows',
  fields: [
    { name: 'id', type: 'uuid', interface: 'input', uiSchema: { title: 'ID' }, primaryKey: true },
    { name: 'naturalKey', type: 'string', interface: 'input', uiSchema: { title: 'Natural Key' }, allowNull: false, unique: true },
    { name: 'planningProductId', type: 'string', interface: 'input', uiSchema: { title: 'Planning Product ID' }, index: true },
    { name: 'calculationDate', type: 'dateOnly', interface: 'date', uiSchema: { title: 'Calculation Date' }, allowNull: false, index: true },
    { name: 'company', type: 'string', interface: 'input', uiSchema: { title: 'Company' }, index: true },
    { name: 'asin', type: 'string', interface: 'input', uiSchema: { title: 'ASIN' }, index: true },
    { name: 'sku', type: 'string', interface: 'input', uiSchema: { title: 'SKU' }, index: true },
    { name: 'title', type: 'text', interface: 'textarea', uiSchema: { title: 'Title' } },
    { name: 'brand', type: 'string', interface: 'input', uiSchema: { title: 'Brand' } },
    { name: 'productStatus', type: 'string', interface: 'input', uiSchema: { title: 'Product Status' }, index: true },
    { name: 'planningExcluded', type: 'boolean', interface: 'checkbox', uiSchema: { title: 'Planning Excluded' }, defaultValue: false },
    { name: 'actionStatus', type: 'string', interface: 'select', uiSchema: { title: 'Action Status', enum: ACTION_STATUS_OPTIONS }, allowNull: false, index: true },
    { name: 'tier', type: 'string', interface: 'select', uiSchema: { title: 'Tier', enum: TIER_OPTIONS }, index: true },
    { name: 'tierScore', type: 'double', interface: 'number', uiSchema: { title: 'Tier Score' } },
    { name: 'profitPerUnit', type: 'double', interface: 'number', uiSchema: { title: 'Profit Per Unit' } },
    { name: 'estimatedProfitRisk', type: 'double', interface: 'number', uiSchema: { title: 'Estimated Profit Risk' } },
    { name: 'recommendedBestQty', type: 'double', interface: 'number', uiSchema: { title: 'Recommended Best Qty' } },
    { name: 'salesVelocity', type: 'double', interface: 'number', uiSchema: { title: 'Sales Velocity' } },
    { name: 'suggestedReorderQty', type: 'double', interface: 'number', uiSchema: { title: 'Suggested Reorder Qty' } },
    { name: 'currentPlanningStock', type: 'double', interface: 'number', uiSchema: { title: 'Current Planning Stock' } },
    { name: 'sellableStock', type: 'double', interface: 'number', uiSchema: { title: 'Sellable Stock' } },
    { name: 'reservedStock', type: 'double', interface: 'number', uiSchema: { title: 'Reserved Stock' } },
    { name: 'pipelineStock', type: 'double', interface: 'number', uiSchema: { title: 'Replenishment Stock' } },
    { name: 'inboundStock', type: 'double', interface: 'number', uiSchema: { title: 'Inbound Stock' } },
    { name: 'orderedStock', type: 'double', interface: 'number', uiSchema: { title: 'Ordered Stock' } },
    { name: 'prepStock', type: 'double', interface: 'number', uiSchema: { title: 'Prep Stock' } },
    { name: 'awdStock', type: 'double', interface: 'number', uiSchema: { title: 'AWD Stock' } },
    { name: 'openOrderCoverageQty', type: 'double', interface: 'number', uiSchema: { title: 'Open Order Coverage Qty' } },
    { name: 'stuck', type: 'boolean', interface: 'checkbox', uiSchema: { title: 'Stuck Inventory' }, defaultValue: false, index: true },
    { name: 'daysOfCover', type: 'double', interface: 'number', uiSchema: { title: 'Days Of Cover' } },
    { name: 'estimatedOosDate', type: 'dateOnly', interface: 'date', uiSchema: { title: 'Estimated OOS Date' }, index: true },
    { name: 'latestSafeReorderDate', type: 'dateOnly', interface: 'date', uiSchema: { title: 'Latest Safe Reorder Date' }, index: true },
    { name: 'daysUntilSafeReorder', type: 'double', interface: 'number', uiSchema: { title: 'Days Until Safe Reorder' } },
    { name: 'supplierId', type: 'string', interface: 'input', uiSchema: { title: 'Supplier ID' } },
    { name: 'supplierName', type: 'string', interface: 'input', uiSchema: { title: 'Supplier Name' }, index: true },
    { name: 'supplierSource', type: 'string', interface: 'input', uiSchema: { title: 'Supplier Source' } },
    { name: 'supplierRole', type: 'string', interface: 'input', uiSchema: { title: 'Supplier Role' } },
    { name: 'supplierConfidence', type: 'string', interface: 'input', uiSchema: { title: 'Supplier Confidence' } },
    { name: 'leadTimeDays', type: 'double', interface: 'number', uiSchema: { title: 'Lead Time Days' } },
    { name: 'leadTimeConfirmedAt', type: 'datetimeTz', interface: 'datetime', uiSchema: { title: 'Lead Time Confirmed At' } },
    { name: 'leadTimeFreshness', type: 'string', interface: 'select', uiSchema: { title: 'Lead Time Freshness', enum: LEAD_TIME_FRESHNESS_OPTIONS }, index: true },
    { name: 'expectedSellableDate', type: 'dateOnly', interface: 'date', uiSchema: { title: 'Expected Sellable Date' } },
    { name: 'digestPriority', type: 'integer', interface: 'integer', uiSchema: { title: 'Digest Priority' }, index: true },
    { name: 'evidence', type: 'jsonb', interface: 'json', uiSchema: { title: 'Evidence' }, defaultValue: {} },
    { name: 'lastRefreshedAt', type: 'datetimeTz', interface: 'datetime', uiSchema: { title: 'Last Refreshed At' }, index: true },
  ],
});
