import { defineCollection } from '@nocobase/database';
import { ECOBASE_COLLECTIONS } from './names';

export default defineCollection({
  migrationRules: ['schema-only'],
  name: ECOBASE_COLLECTIONS.inventorySnapshots,
  title: 'Ecobase inventory snapshots',
  fields: [
    {
      name: 'naturalKey',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Natural Key' },
      allowNull: false,
      unique: true,
    },
    {
      name: 'sourceConnectionId',
      type: 'uuid',
      interface: 'input',
      uiSchema: { title: 'Source Connection ID' },
      allowNull: false,
      autoFill: false,
      index: true,
    },
    {
      name: 'planningProductId',
      type: 'uuid',
      interface: 'input',
      uiSchema: { title: 'Planning Product ID' },
      autoFill: false,
      index: true,
    },
    {
      name: 'snapshotDate',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Snapshot Date' },
      allowNull: false,
      index: true,
    },
    { name: 'company', type: 'string', interface: 'input', uiSchema: { title: 'Company' }, index: true },
    { name: 'asin', type: 'string', interface: 'input', uiSchema: { title: 'ASIN' }, index: true },
    { name: 'sku', type: 'string', interface: 'input', uiSchema: { title: 'SKU' }, index: true },
    { name: 'stock', type: 'double', interface: 'number', uiSchema: { title: 'Stock' } },
    { name: 'reserved', type: 'double', interface: 'number', uiSchema: { title: 'Reserved' } },
    { name: 'inbound', type: 'double', interface: 'number', uiSchema: { title: 'Inbound' } },
    { name: 'ordered', type: 'double', interface: 'number', uiSchema: { title: 'Ordered' } },
    { name: 'prepStock', type: 'double', interface: 'number', uiSchema: { title: 'Prep Stock' } },
    { name: 'salesVelocity', type: 'double', interface: 'number', uiSchema: { title: 'Sales Velocity' } },
    { name: 'daysOfStockLeft', type: 'double', interface: 'number', uiSchema: { title: 'Days Of Stock Left' } },
    {
      name: 'recommendedReorderQuantity',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Recommended Reorder Quantity' },
    },
    { name: 'payload', type: 'jsonb', interface: 'json', uiSchema: { title: 'Payload' }, defaultValue: {} },
    {
      name: 'lastImportRunId',
      type: 'uuid',
      interface: 'input',
      uiSchema: { title: 'Last Import Run ID' },
      autoFill: false,
      index: true,
    },
  ],
});
