export const ECOBASE_COLLECTIONS = {
  companies: 'ecobaseCompanies',
  amazonAccounts: 'ecobaseAmazonAccounts',
  sourceConnections: 'ecobaseSourceConnections',
  importRuns: 'ecobaseImportRuns',
  rawImportRows: 'ecobaseRawImportRows',
  rawListings: 'ecobaseRawListings',
  planningProducts: 'ecobasePlanningProducts',
  planningProductListings: 'ecobasePlanningProductListings',
  planningProductMappingAudits: 'ecobasePlanningProductMappingAudits',
  listingDailyFacts: 'ecobaseListingDailyFacts',
  inventorySnapshots: 'ecobaseInventorySnapshots',
  inventoryPlanningRows: 'ecobaseInventoryPlanningRows',
  trafficSnapshots: 'ecobaseTrafficSnapshots',
  planningParameters: 'ecobasePlanningParameters',
  suppliers: 'ecobaseSuppliers',
  supplierLeadTimes: 'ecobaseSupplierLeadTimes',
  supplierExternalIdentities: 'ecobaseSupplierExternalIdentities',
  supplierProductLinks: 'ecobaseSupplierProductLinks',
  supplierOrders: 'ecobaseSupplierOrders',
  supplierOrderLines: 'ecobaseSupplierOrderLines',
  supplierOrderActivities: 'ecobaseSupplierOrderActivities',
  supplierOrderSettings: 'ecobaseSupplierOrderSettings',
  targetRows: 'ecobaseTargetRows',
  planningCalculationSnapshots: 'ecobasePlanningCalculationSnapshots',
  ruleVersions: 'ecobaseRuleVersions',
  alertEvaluations: 'ecobaseAlertEvaluations',
  alerts: 'ecobaseAlerts',
  clickupTaskSnapshots: 'ecobaseClickupTaskSnapshots',
  taskLinks: 'ecobaseTaskLinks',
  okrs: 'ecobaseOkrs',
  okrMetricSnapshots: 'ecobaseOkrMetricSnapshots',
  sourceAccessAudits: 'ecobaseSourceAccessAudits',
  sourceWarningPolicies: 'ecobaseSourceWarningPolicies',
  reportRuns: 'ecobaseReportRuns',
  reportItems: 'ecobaseReportItems',
  aiAnswers: 'ecobaseAiAnswers',
  dataQualitySignoffs: 'ecobaseDataQualitySignoffs',
  benchmarkFixtures: 'ecobaseBenchmarkFixtures',
  accuracyEvaluationRuns: 'ecobaseAccuracyEvaluationRuns',
} as const;

export type EcobaseCollectionName = (typeof ECOBASE_COLLECTIONS)[keyof typeof ECOBASE_COLLECTIONS];
