import { defineCollection } from '@nocobase/database';
import { ECOBASE_COLLECTIONS } from './names';

export default defineCollection({
  migrationRules: ['schema-only'],
  name: ECOBASE_COLLECTIONS.planningCalculationSnapshots,
  title: 'Ecobase planning calculation snapshots',
  fields: [
    {
      name: 'naturalKey',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Natural Key' },
      allowNull: false,
      unique: true,
    },
    {
      name: 'planningProductId',
      type: 'uuid',
      interface: 'input',
      uiSchema: { title: 'Planning Product ID' },
      allowNull: false,
      autoFill: false,
      index: true,
    },
    {
      name: 'calculationDate',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Calculation Date' },
      allowNull: false,
      index: true,
    },
    {
      name: 'ruleVersion',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Rule Version' },
      allowNull: false,
      defaultValue: 'spreadsheet_parity_v1',
      index: true,
    },
    { name: 'company', type: 'string', interface: 'input', uiSchema: { title: 'Company' }, index: true },
    { name: 'canonicalAsin', type: 'string', interface: 'input', uiSchema: { title: 'Canonical ASIN' }, index: true },
    {
      name: 'tier',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Tier' },
      allowNull: false,
      defaultValue: 'unclassified',
      index: true,
    },
    { name: 'tierScore', type: 'double', interface: 'number', uiSchema: { title: 'Tier Score' } },
    { name: 'currentStockParity', type: 'double', interface: 'number', uiSchema: { title: 'Current Stock Parity' } },
    { name: 'sellableStock', type: 'double', interface: 'number', uiSchema: { title: 'Sellable Stock' } },
    { name: 'pipelineStock', type: 'double', interface: 'number', uiSchema: { title: 'Replenishment Stock' } },
    { name: 'salesVelocity', type: 'double', interface: 'number', uiSchema: { title: 'Sales Velocity' } },
    { name: 'daysOfCover', type: 'double', interface: 'number', uiSchema: { title: 'Days Of Cover' } },
    { name: 'oosDate', type: 'string', interface: 'input', uiSchema: { title: 'OOS date' } },
    { name: 'leadTimeDays', type: 'double', interface: 'number', uiSchema: { title: 'Lead Time Days' } },
    {
      name: 'safetyBufferDays',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Safety Buffer Days' },
      allowNull: false,
      defaultValue: 7,
    },
    {
      name: 'restockDeadlineParity',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Restock Deadline Parity' },
    },
    {
      name: 'restockDeadlineImproved',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Restock Deadline Improved' },
    },
    {
      name: 'latestSafeReorderWindowStart',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Latest Safe Reorder Window Start' },
    },
    {
      name: 'latestSafeReorderWindowEnd',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Latest Safe Reorder Window End' },
    },
    { name: 'daysLeftOrOverdue', type: 'double', interface: 'number', uiSchema: { title: 'Days Left Or Overdue' } },
    {
      name: 'urgentRestock',
      type: 'boolean',
      interface: 'checkbox',
      uiSchema: { title: 'Urgent Restock' },
      defaultValue: false,
      index: true,
    },
    {
      name: 'restockNeeded',
      type: 'boolean',
      interface: 'checkbox',
      uiSchema: { title: 'Restock Needed' },
      defaultValue: false,
      index: true,
    },
    {
      name: 'estimatedMonthEndQuantity',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Estimated Month End Quantity' },
    },
    { name: 'recommendedBestQty', type: 'double', interface: 'number', uiSchema: { title: 'Recommended Best Qty' } },
    { name: 'profitPerUnit', type: 'double', interface: 'number', uiSchema: { title: 'Profit Per Unit' } },
    { name: 'achievedProfitMtd', type: 'double', interface: 'number', uiSchema: { title: 'Achieved Profit MTD' } },
    {
      name: 'proratedProfitTargetMtd',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Prorated Profit Target MTD' },
    },
    { name: 'profitGap', type: 'double', interface: 'number', uiSchema: { title: 'Profit Gap' } },
    {
      name: 'profitOffTrack',
      type: 'boolean',
      interface: 'checkbox',
      uiSchema: { title: 'Profit Off Track' },
      defaultValue: false,
      index: true,
    },
    { name: 'estimatedProfitRisk', type: 'double', interface: 'number', uiSchema: { title: 'Estimated Profit Risk' } },
    {
      name: 'dataCompleteness',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Data Completeness' },
      allowNull: false,
      index: true,
    },
    {
      name: 'calculationStatus',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Calculation Status' },
      allowNull: false,
      index: true,
    },
    { name: 'evidence', type: 'jsonb', interface: 'json', uiSchema: { title: 'Evidence' }, defaultValue: {} },
    {
      name: 'lastImportRunId',
      type: 'uuid',
      interface: 'input',
      uiSchema: { title: 'Last Import Run ID' },
      autoFill: false,
      index: true,
    },
  ],
});
