import { defineCollection } from '@nocobase/database';
import { ECOBASE_COLLECTIONS } from './names';

export default defineCollection({
  migrationRules: ['schema-only'],
  autoGenId: false,
  name: ECOBASE_COLLECTIONS.planningProducts,
  title: 'Ecobase planning products',
  fields: [
    { name: 'id', type: 'uuid', interface: 'input', uiSchema: { title: 'ID' }, primaryKey: true },
    {
      name: 'naturalKey',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Natural Key' },
      allowNull: false,
      unique: true,
    },
    {
      name: 'company',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Company' },
      allowNull: false,
      index: true,
    },
    {
      name: 'canonicalAsin',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Canonical ASIN' },
      allowNull: false,
      index: true,
    },
    { name: 'title', type: 'text', interface: 'textarea', uiSchema: { title: 'Title' } },
    {
      name: 'mappingStatus',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Mapping Status' },
      allowNull: false,
      defaultValue: 'auto_mapped',
      index: true,
    },
    {
      name: 'listingCount',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Listing Count' },
      allowNull: false,
      defaultValue: 0,
    },
    {
      name: 'lastImportRunId',
      type: 'uuid',
      interface: 'input',
      uiSchema: { title: 'Last Import Run ID' },
      autoFill: false,
      index: true,
    },
    { name: 'confirmedAt', type: 'datetimeTz', interface: 'datetime', uiSchema: { title: 'Confirmed At' } },
    { name: 'confirmedBy', type: 'string', interface: 'input', uiSchema: { title: 'Confirmed By' } },
    { name: 'auditSummary', type: 'jsonb', interface: 'json', uiSchema: { title: 'Audit Summary' }, defaultValue: {} },
    {
      name: 'listings',
      type: 'hasMany',
      target: ECOBASE_COLLECTIONS.planningProductListings,
      foreignKey: 'planningProductId',
      onDelete: 'CASCADE',
    },
  ],
});
