import { defineCollection } from '@nocobase/database';
import { ECOBASE_COLLECTIONS } from './names';

export default defineCollection({
  migrationRules: ['schema-only'],
  name: ECOBASE_COLLECTIONS.planningCalculationSnapshots,
  title: 'Ecobase planning calculation snapshots',
  fields: [
    { name: 'naturalKey', type: 'string', allowNull: false, unique: true },
    { name: 'planningProductId', type: 'uuid', allowNull: false, autoFill: false, index: true },
    { name: 'calculationDate', type: 'string', allowNull: false, index: true },
    { name: 'ruleVersion', type: 'string', allowNull: false, defaultValue: 'spreadsheet_parity_v1', index: true },
    { name: 'company', type: 'string', index: true },
    { name: 'canonicalAsin', type: 'string', index: true },
    { name: 'tier', type: 'string', allowNull: false, defaultValue: 'unclassified', index: true },
    { name: 'tierScore', type: 'double' },
    { name: 'currentStockParity', type: 'double' },
    { name: 'sellableStock', type: 'double' },
    { name: 'pipelineStock', type: 'double' },
    { name: 'salesVelocity', type: 'double' },
    { name: 'daysOfCover', type: 'double' },
    { name: 'oosDate', type: 'string' },
    { name: 'leadTimeDays', type: 'double' },
    { name: 'safetyBufferDays', type: 'double', allowNull: false, defaultValue: 7 },
    { name: 'restockDeadlineParity', type: 'string' },
    { name: 'restockDeadlineImproved', type: 'string' },
    { name: 'latestSafeReorderWindowStart', type: 'string' },
    { name: 'latestSafeReorderWindowEnd', type: 'string' },
    { name: 'daysLeftOrOverdue', type: 'double' },
    { name: 'urgentRestock', type: 'boolean', defaultValue: false, index: true },
    { name: 'restockNeeded', type: 'boolean', defaultValue: false, index: true },
    { name: 'estimatedMonthEndQuantity', type: 'double' },
    { name: 'recommendedBestQty', type: 'double' },
    { name: 'profitPerUnit', type: 'double' },
    { name: 'achievedProfitMtd', type: 'double' },
    { name: 'proratedProfitTargetMtd', type: 'double' },
    { name: 'profitGap', type: 'double' },
    { name: 'profitOffTrack', type: 'boolean', defaultValue: false, index: true },
    { name: 'estimatedProfitRisk', type: 'double' },
    { name: 'dataCompleteness', type: 'string', allowNull: false, index: true },
    { name: 'calculationStatus', type: 'string', allowNull: false, index: true },
    { name: 'evidence', type: 'jsonb', defaultValue: {} },
    { name: 'lastImportRunId', type: 'uuid', autoFill: false, index: true },
  ],
});
