import { defineCollection } from '@nocobase/database';
import { ECOBASE_COLLECTIONS } from './names';

export default defineCollection({
  migrationRules: ['schema-only'],
  autoGenId: false,
  name: ECOBASE_COLLECTIONS.silverOrderLines,
  title: 'Silver order lines',
  fields: [
    { name: 'id', type: 'uuid', primaryKey: true },
    {
      name: 'order',
      type: 'belongsTo',
      target: ECOBASE_COLLECTIONS.silverOrders,
      foreignKey: 'orderId',
      targetKey: 'id',
      onDelete: 'CASCADE',
    },
    {
      name: 'companyProduct',
      type: 'belongsTo',
      target: ECOBASE_COLLECTIONS.silverCompanyProducts,
      foreignKey: 'companyProductId',
      targetKey: 'id',
      onDelete: 'RESTRICT',
    },
    {
      name: 'supplierProduct',
      type: 'belongsTo',
      target: ECOBASE_COLLECTIONS.silverSupplierProducts,
      foreignKey: 'supplierProductId',
      targetKey: 'id',
      onDelete: 'RESTRICT',
    },
    { name: 'sourceLineKey', type: 'string', allowNull: false },
    { name: 'orderedQty', type: 'double', allowNull: false },
    { name: 'confirmedQty', type: 'double' },
    { name: 'unitCost', type: 'double' },
    { name: 'expectedSellPrice', type: 'double' },
    { name: 'expectedMargin', type: 'double' },
    { name: 'expectedProfit', type: 'double' },
    { name: 'supplierPackSize', type: 'double' },
    { name: 'fbaExpectedPackSize', type: 'double' },
    { name: 'prepInstruction', type: 'text' },
    { name: 'expectedDeliveryDate', type: 'dateOnly' },
    { name: 'expectedSellableDate', type: 'dateOnly' },
    { name: 'expectedArrivalDate', type: 'dateOnly' },
    { name: 'expectedArrivalStatus', type: 'string', allowNull: false, defaultValue: 'unknown' },
    { name: 'expectedArrivalSource', type: 'string' },
    { name: 'expectedArrivalAsOf', type: 'dateOnly' },
    { name: 'expectedArrivalConfidence', type: 'string', allowNull: false, defaultValue: 'none' },
    { name: 'upc', type: 'string' },
    { name: 'mapPrice', type: 'double' },
    { name: 'productAnalysisStatus', type: 'string', allowNull: false, defaultValue: 'unknown' },
    { name: 'priority', type: 'string' },
  ],
  indexes: [
    {
      unique: true,
      fields: ['orderId', 'sourceLineKey'],
    },
    {
      fields: ['orderId', 'companyProductId'],
    },
  ],
});
