import { defineCollection } from '@nocobase/database';
import { ECOBASE_COLLECTIONS } from './names';

export default defineCollection({
  migrationRules: ['schema-only'],
  autoGenId: false,
  name: ECOBASE_COLLECTIONS.supplierOrderLines,
  title: 'Ecobase supplier order lines',
  fields: [
    { name: 'id', type: 'uuid', interface: 'input', uiSchema: { title: 'ID' }, primaryKey: true },
    {
      name: 'naturalKey',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Natural Key' },
      allowNull: false,
      unique: true,
    },
    {
      name: 'supplierOrderId',
      type: 'uuid',
      interface: 'input',
      uiSchema: { title: 'Supplier Order ID' },
      allowNull: false,
      autoFill: false,
      index: true,
    },
    {
      name: 'company',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Company' },
      allowNull: false,
      index: true,
    },
    {
      name: 'supplierId',
      type: 'uuid',
      interface: 'input',
      uiSchema: { title: 'Supplier ID' },
      allowNull: false,
      autoFill: false,
      index: true,
    },
    {
      name: 'planningProductId',
      type: 'uuid',
      interface: 'input',
      uiSchema: { title: 'Planning Product ID' },
      autoFill: false,
      index: true,
    },
    { name: 'asin', type: 'string', interface: 'input', uiSchema: { title: 'ASIN' }, index: true },
    { name: 'sku', type: 'string', interface: 'input', uiSchema: { title: 'SKU' }, index: true },
    { name: 'brand', type: 'string', interface: 'input', uiSchema: { title: 'Brand' }, index: true },
    { name: 'orderedQty', type: 'double', interface: 'number', uiSchema: { title: 'Ordered Qty' }, allowNull: false },
    {
      name: 'receivedQty',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Received Qty' },
      allowNull: false,
      defaultValue: 0,
    },
    {
      name: 'receivedQtySource',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Received Qty Source' },
      allowNull: false,
      defaultValue: 'import',
    },
    { name: 'expectedDeliveryDate', type: 'string', interface: 'input', uiSchema: { title: 'Expected Delivery Date' } },
    { name: 'expectedSellableDate', type: 'string', interface: 'input', uiSchema: { title: 'Expected Sellable Date' } },
    {
      name: 'expectedSellableDateSource',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Expected Sellable Date Source' },
      allowNull: false,
      defaultValue: 'missing',
    },
    {
      name: 'expectedSellableDateEvidence',
      type: 'jsonb',
      interface: 'json',
      uiSchema: { title: 'Expected Sellable Date Evidence' },
      defaultValue: {},
    },
    {
      name: 'expectedSellableDateDerivedAt',
      type: 'datetimeTz',
      interface: 'datetime',
      uiSchema: { title: 'Expected Sellable Date Derived At' },
    },
    {
      name: 'lastOperatorEditAt',
      type: 'datetimeTz',
      interface: 'datetime',
      uiSchema: { title: 'Last Operator Edit At' },
    },
    { name: 'lastOperatorActor', type: 'string', interface: 'input', uiSchema: { title: 'Last Operator Actor' } },
    { name: 'unitCost', type: 'double', interface: 'number', uiSchema: { title: 'Unit Cost' } },
    {
      name: 'sourceOrderLineRef',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Source Order Line Ref' },
      allowNull: false,
      index: true,
    },
    {
      name: 'sourceStage',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Source Stage' },
      allowNull: false,
      index: true,
    },
    { name: 'observedAt', type: 'datetimeTz', interface: 'datetime', uiSchema: { title: 'Observed At' } },
    {
      name: 'unresolvedMapping',
      type: 'boolean',
      interface: 'checkbox',
      uiSchema: { title: 'Unresolved Mapping' },
      allowNull: false,
      defaultValue: false,
    },
    { name: 'mappingWarning', type: 'text', interface: 'textarea', uiSchema: { title: 'Mapping Warning' } },
    { name: 'payload', type: 'jsonb', interface: 'json', uiSchema: { title: 'Payload' }, defaultValue: {} },
    {
      name: 'lastImportRunId',
      type: 'uuid',
      interface: 'input',
      uiSchema: { title: 'Last Import Run ID' },
      index: true,
    },
  ],
});
