import { defineCollection } from '@nocobase/database';
import { ECOBASE_COLLECTIONS } from './names';

export default defineCollection({
  migrationRules: ['schema-only'],
  autoGenId: false,
  name: ECOBASE_COLLECTIONS.supplierAttentionRows,
  title: 'Ecobase supplier attention rows',
  fields: [
    { name: 'id', type: 'uuid', interface: 'input', uiSchema: { title: 'ID' }, primaryKey: true },
    {
      name: 'naturalKey',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Natural Key' },
      allowNull: false,
      unique: true,
    },
    {
      name: 'company',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Company' },
      allowNull: false,
      index: true,
    },
    {
      name: 'supplierId',
      type: 'uuid',
      interface: 'input',
      uiSchema: { title: 'Supplier ID' },
      allowNull: false,
      autoFill: false,
      index: true,
    },
    { name: 'supplierName', type: 'string', interface: 'input', uiSchema: { title: 'Supplier Name' }, index: true },
    { name: 'approvalStatus', type: 'string', interface: 'input', uiSchema: { title: 'Approval Status' }, index: true },
    { name: 'accountStatus', type: 'string', interface: 'input', uiSchema: { title: 'Account Status' }, index: true },
    { name: 'analysisStatus', type: 'string', interface: 'input', uiSchema: { title: 'Analysis Status' }, index: true },
    {
      name: 'calculationDate',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Calculation Date' },
      allowNull: false,
      index: true,
    },
    {
      name: 'attentionStatus',
      type: 'string',
      interface: 'select',
      uiSchema: {
        title: 'Attention Status',
        enum: [
          { label: 'Urgent', value: 'urgent' },
          { label: 'Needs attention', value: 'needs_attention' },
          { label: 'Monitor', value: 'monitor' },
          { label: 'OK', value: 'ok' },
        ],
      },
      allowNull: false,
      index: true,
    },
    {
      name: 'attentionScore',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Attention Score' },
      defaultValue: 0,
    },
    { name: 'recommendedAction', type: 'string', interface: 'input', uiSchema: { title: 'Recommended Action' } },
    { name: 'reasonCodes', type: 'jsonb', interface: 'json', uiSchema: { title: 'Reason Codes' }, defaultValue: [] },
    {
      name: 'urgentProductCount',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Urgent Product Count' },
      defaultValue: 0,
    },
    {
      name: 'oosSoonProductCount',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'OOS Soon Product Count' },
      defaultValue: 0,
    },
    {
      name: 'earliestEstimatedOosDate',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Earliest Estimated OOS Date' },
      index: true,
    },
    {
      name: 'highestEstimatedProfitRisk',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Highest Estimated Profit Risk' },
      defaultValue: 0,
    },
    {
      name: 'totalEstimatedProfitRisk',
      type: 'double',
      interface: 'number',
      uiSchema: { title: 'Total Estimated Profit Risk' },
      defaultValue: 0,
    },
    {
      name: 'leadTimeIssueCount',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Lead-Time Issue Count' },
      defaultValue: 0,
    },
    {
      name: 'missingLeadTimeCount',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Missing Lead-Time Count' },
      defaultValue: 0,
    },
    {
      name: 'staleLeadTimeCount',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Stale Lead-Time Count' },
      defaultValue: 0,
    },
    {
      name: 'conflictingLeadTimeCount',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Conflicting Lead-Time Count' },
      defaultValue: 0,
    },
    {
      name: 'openOrderCount',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Open Order Count' },
      defaultValue: 0,
    },
    {
      name: 'lateOpenOrderCount',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Late Open Order Count' },
      defaultValue: 0,
    },
    {
      name: 'blockedOpenOrderCount',
      type: 'integer',
      interface: 'integer',
      uiSchema: { title: 'Blocked Open Order Count' },
      defaultValue: 0,
    },
    { name: 'lastContactedAt', type: 'datetimeTz', interface: 'datetime', uiSchema: { title: 'Last Contacted At' } },
    { name: 'nextFollowUpAt', type: 'datetimeTz', interface: 'datetime', uiSchema: { title: 'Next Follow-Up At' } },
    {
      name: 'contactSoon',
      type: 'boolean',
      interface: 'checkbox',
      uiSchema: { title: 'Contact Soon' },
      allowNull: false,
      defaultValue: false,
      index: true,
    },
    {
      name: 'contactStatus',
      type: 'string',
      interface: 'select',
      uiSchema: {
        title: 'Contact Status',
        enum: [
          { label: 'Overdue', value: 'overdue' },
          { label: 'Due soon', value: 'due_soon' },
          { label: 'Recent', value: 'recent' },
          { label: 'Missing', value: 'missing' },
        ],
      },
      index: true,
    },
    { name: 'evidence', type: 'jsonb', interface: 'json', uiSchema: { title: 'Evidence' }, defaultValue: {} },
    { name: 'lastRefreshedAt', type: 'datetimeTz', interface: 'datetime', uiSchema: { title: 'Last Refreshed At' } },
  ],
});
