import { defineCollection } from '@nocobase/database';
import { ECOBASE_COLLECTIONS } from './names';

export default defineCollection({
  migrationRules: ['schema-only'],
  autoGenId: false,
  name: ECOBASE_COLLECTIONS.supplierOrders,
  title: 'Ecobase supplier orders',
  fields: [
    { name: 'id', type: 'uuid', interface: 'input', uiSchema: { title: 'ID' }, primaryKey: true },
    {
      name: 'naturalKey',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Natural Key' },
      allowNull: false,
      unique: true,
    },
    {
      name: 'sourceConnectionId',
      type: 'uuid',
      interface: 'input',
      uiSchema: { title: 'Source Connection ID' },
      allowNull: false,
      index: true,
    },
    {
      name: 'company',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Company' },
      allowNull: false,
      index: true,
    },
    {
      name: 'supplierId',
      type: 'uuid',
      interface: 'input',
      uiSchema: { title: 'Supplier ID' },
      allowNull: false,
      autoFill: false,
      index: true,
    },
    {
      name: 'externalOrderRef',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'External Order Ref' },
      index: true,
    },
    {
      name: 'sourceStage',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Source Stage' },
      allowNull: false,
      index: true,
    },
    {
      name: 'status',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Status' },
      allowNull: false,
      index: true,
    },
    {
      name: 'statusSource',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Status Source' },
      allowNull: false,
      defaultValue: 'import',
    },
    { name: 'statusUpdatedAt', type: 'datetimeTz', interface: 'datetime', uiSchema: { title: 'Status Updated At' } },
    {
      name: 'lastMeaningfulUpdateAt',
      type: 'datetimeTz',
      interface: 'datetime',
      uiSchema: { title: 'Last Meaningful Update At' },
    },
    {
      name: 'lastOperatorEditAt',
      type: 'datetimeTz',
      interface: 'datetime',
      uiSchema: { title: 'Last Operator Edit At' },
    },
    { name: 'lastOperatorActor', type: 'string', interface: 'input', uiSchema: { title: 'Last Operator Actor' } },
    { name: 'orderDate', type: 'string', interface: 'input', uiSchema: { title: 'Order Date' } },
    { name: 'expectedDeliveryDate', type: 'string', interface: 'input', uiSchema: { title: 'Expected Delivery Date' } },
    {
      name: 'expectedDeliveryDateSource',
      type: 'string',
      interface: 'input',
      uiSchema: { title: 'Expected Delivery Date Source' },
      allowNull: false,
      defaultValue: 'missing',
    },
    { name: 'approvalStatus', type: 'string', interface: 'input', uiSchema: { title: 'Approval Status' } },
    { name: 'paymentStatus', type: 'string', interface: 'input', uiSchema: { title: 'Payment Status' } },
    { name: 'shippingCarrier', type: 'string', interface: 'input', uiSchema: { title: 'Shipping Carrier' } },
    { name: 'trackingId', type: 'text', interface: 'textarea', uiSchema: { title: 'Tracking ID' } },
    { name: 'blockedReason', type: 'text', interface: 'textarea', uiSchema: { title: 'Blocked Reason' } },
    { name: 'payload', type: 'jsonb', interface: 'json', uiSchema: { title: 'Payload' }, defaultValue: {} },
    {
      name: 'lastImportRunId',
      type: 'uuid',
      interface: 'input',
      uiSchema: { title: 'Last Import Run ID' },
      index: true,
    },
  ],
});
