/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */

/**
 * Single source of every user-facing literal on the Inventory Dashboard
 * (AD-8 / T-2.5). Components must reference `TEXT.*` (never inline strings) so
 * the i18n parity test can mechanically assert that every key exists in both
 * `en-US.json` and `zh-CN.json`.
 */

export const TEXT = {
  pageTitle: 'Inventory Dashboard',
  publishedRun: 'Published run',
  searchLabel: 'Search',
  searchPlaceholder: 'Search products or orders',
  companyFilterLabel: 'Company',
  allCompanies: 'All companies',
  refresh: 'Refresh',
  retry: 'Retry',
  loadFailed: 'Failed to load',
  unexpectedResponse: 'Unexpected server response shape',
  empty: 'No rows',
  loading: 'Loading',
  slowLoadHint: 'Still loading — the first request after a restart can take up to a minute',
  unknown: 'unknown',
  days: 'days',
  noActivityYet: 'no activity yet',
  runSupersededNotice: 'Data updated — refresh to load the latest published run',
  paneSupplyAction: 'Supply Action',
  paneActiveOrders: 'Active Orders',
  paneInPrepMonitoring: 'In-Prep Monitoring',
  paneInboundMonitoring: 'Inbound Monitoring',
  paneHealthyInventory: 'Healthy Inventory',
  paneExcessInventory: 'Excess Inventory',
  paneStuckInventory: 'Stuck Inventory',
  paneZeroStock: 'Zero Stock',
  paneDataReadiness: 'Data Readiness',
  panePerformanceReview: 'Performance Review',
  paneUntieredProducts: 'Untiered Products',
  paneDiscontinuedPaused: 'Discontinued & Paused',
  tileUrgentStockout: 'Urgent stockout risk',
  tileOrderedButLate: 'Ordered but late',
  tileStaleLeadTimes: 'Stale lead times',
  tileNeedsFollowUp: 'Needs follow-up',
  tileStuckCapital: 'Stuck capital',
  metricRows: 'Rows',
  metricMoneyAtRisk: 'Money at risk',
  metricUnknownMoney: 'Unknown money inputs',
  colProduct: 'Product',
  colOrder: 'Order',
  colReorderBy: 'Reorder by',
  colEstOos: 'Est. out of stock',
  colDaysOfCover: 'Days of cover',
  colProfitRisk: 'Profit risk',
  colDaysInStage: 'Days in stage',
  colLastActivity: 'Last activity',
  colExpectedArrival: 'Expected arrival',
  colStock: 'Stock',
  colUnitCost: 'Unit cost',
  colSignals: 'Signals',
  colMembers: 'Members',
  colLastMovement: 'Last movement',
  paneSearchPlaceholder: 'Search this pane',
  drawerReactivate: 'Reactivate',
  drawerAssignSupplier: 'Assign supplier',
  metricTieredNeedingAttention: 'Tiered families needing attention',
  drawerPreviousStatus: 'Previous status',
  drawerFamilyTarget: 'Family target',
  drawerNoTargetInReview: 'none (target in review)',
  toastFamilyReactivated: 'Family reactivated — it returns to normal classification on the next publish',
  toastSupplierAssigned: 'Supplier assigned',
  drawerReactivateReason: 'Reactivation reason (required)',
  tier: 'Tier',
  badgeStale: 'Stale data',
  badgeFamilySplit: 'Family split',
  badgeUntieredProjected: 'Untiered (projected)',
  reasonFrozenFamilyTargetReview: 'Family target review',
  reasonMissingBaselineEvidence: 'Missing baseline evidence',
  reasonFamilyReviewRequired: 'Family review required',
  badgeDirectFba: 'Direct FBA',
  badgeOwnPrep: 'Own prep center',
  badgePrepUnknown: 'Prep path unknown',
  bufferSufficient: 'On time',
  bufferAtRisk: 'At risk',
  bufferLate: 'Late',
  bufferUnknown: 'Arrival unknown',
  trendUp: 'Trending up',
  trendFlat: 'Flat',
  trendDown: 'Trending down',
  trendUnknown: 'Trend unknown',
  bandAbove: 'Above band',
  bandWithin: 'Within band',
  bandBelow: 'Below band',
  bandInsufficient: 'Insufficient evidence',
  drawerStatus: 'Status',
  drawerSupplier: 'Supplier',
  drawerFamilyListings: 'Family listings',
  drawerComment: 'Comment',
  drawerAddComment: 'Add comment',
  drawerChangeStatus: 'Change status',
  drawerPrepDetails: 'Prep details',
  drawerBoxes: 'Boxes',
  drawerCartons: 'Cartons',
  drawerSavePrepDetails: 'Save prep details',
  drawerShipRoute: 'Set supplier ship route',
  drawerShipsDirect: 'Ships direct to FBA',
  drawerShipsPrepCenter: 'Ships to our prep center',
  drawerSave: 'Save',
  drawerAdjustEta: 'Adjust expected delivery',
  drawerReason: 'Reason',
  drawerBufferExplanation: 'Buffer compares expected arrival with the estimated stockout date minus the safety buffer.',
  drawerSuggestedQty: 'Suggested order quantity',
  drawerOpenOrderPlanning: 'Open in Order Planning',
  drawerStuckReasons: 'Stuck reasons',
  drawerReadinessReasons: 'Readiness reasons',
  drawerOpenInventoryPlanning: 'Open Inventory Planning',
  drawerOpenSupplierManagement: 'Open Supplier Management',
  drawerBandTitle: 'Monthly units (last closed months)',
  drawerTierEvidence: 'Tier evidence',
  drawerFollowUpAck: 'Follow-up acknowledged.',
  drawerAcknowledgeFollowUp: 'Acknowledge follow-up',
  // T7 — Supply Action v2 table + widgets.
  colVelocityCover: 'Velocity & cover',
  colOrderBy: 'Order by',
  colOrderQty: 'Order qty',
  colAction: 'Action',
  unitsSuffix: 'units',
  bucketFba: 'FBA',
  bucketRsv: 'Rsv',
  bucketInb: 'Inb',
  bucketPrep: 'Prep',
  bucketOrd: 'Ord',
  bucketAwd: 'AWD',
  bucketReserved: 'Reserved',
  bucketInbound: 'Inbound',
  bucketOrdered: 'Ordered',
  perDay: '/day',
  dSuffix: 'd',
  coverWord: 'cover',
  oosPrefix: 'OOS',
  estimateFromPrefix: 'estimate — from',
  relPassed: 'passed',
  relInPrefix: 'in',
  dOldSuffix: 'd old',
  actionOverdue: 'Overdue — order today',
  actionRefreshLeadTime: 'Refresh lead time',
  actionVerifyVelocity: 'Verify velocity',
  actionOrderThisWeek: 'Order this week',
  actionOrderSoon: 'Order soon',
  targetPrefix: 'Target:',
  reasonEstimatedVelocity: 'Estimated velocity',
  syncing: 'syncing',
  syncTooltip: 'edited — publishes with the next run (~45 s)',
  syncChip: 'syncs after next publish',
  toastTargetChanged: 'Family target updated',
  metricNeedOrdering: 'need ordering',
  metricAtRiskSuffix: 'at risk',
  onlyMemberNote: 'Only member of its family',
  coversPrefix: 'covers',
  reasonRequiredLabel: 'Reason (required)',
  // T8b — Supply Action drawer v2.
  btnCreateOrder: 'Create order',
  btnChangeTarget: 'Change target…',
  btnChangeSupplier: 'Change supplier…',
  btnUpdateLeadTime: 'Update lead time…',
  btnSetStatus: 'Set status…',
  tabOverview: 'Overview',
  tabOrders: 'Orders',
  tabComments: 'Comments',
  tabData: 'Data',
  chartTitle: 'Profit performance — last 6 closed months',
  chartMonthlyProfit: 'monthly profit',
  chartBestLegend: 'best month — dot on the green line',
  chartWorstLegend: 'worst month — dot on the red line',
  chartDotsLegend: 'big dot = latest closed · hollow dot = this month, projected',
  chartBestPrefix: 'best',
  chartWorstPrefix: 'worst',
  chartProj: 'proj.',
  chartInsufficient: 'Not enough closed months for the chart',
  keyNumbers: 'Key numbers',
  statVelocity: 'Velocity',
  statProfitPerUnit: 'Profit / unit',
  statProfitPerMonth: 'Profit / month',
  stockBucketsTitle: 'Stock buckets',
  orderHistoryTitle: 'Order history',
  maxEverPrefix: 'max ever:',
  noOrdersYet: 'No supplier orders on record',
  commentsTitle: 'Comments — product, orders & supplier',
  commentPlaceholder: 'Write a comment…',
  btnPost: 'Post',
  entityProduct: 'product',
  entityFamily: 'family',
  entityOrder: 'order',
  entitySupplier: 'supplier',
  noCommentsYet: 'No comments yet',
  dataSearchPlaceholder: 'Filter fields',
  dataField: 'Field',
  dataValue: 'Value',
  qtyLabel: 'Quantity',
  expectedDeliveryLabel: 'Expected delivery (YYYY-MM-DD)',
  expectedSellableLabel: 'Expected sellable (YYYY-MM-DD)',
  notesLabel: 'Notes',
  toastOrderCreated: 'Draft order created',
  leadTimeDaysLabel: 'Lead time days',
  evidenceNotesLabel: 'Evidence notes',
  toastLeadTimeUpdated: 'Lead time updated',
  planningIncludedLabel: 'Planning inclusion',
  includedOption: 'Included',
  excludedOption: 'Excluded',
  reorderCycleLabel: 'Reorder cycle days',
  targetCoverLabel: 'Target cover days',
  toastStatusSaved: 'Planning fields updated',
  toastCommentPosted: 'Comment posted',
  relHoursAgo: 'h ago',
  relDaysAgo: 'd ago',
  relJustNow: 'just now',
  relYesterday: 'yesterday',
  // T-D5 (approved OPEN-D5): urgent-stockout badge for non-action panes.
  urgentStockoutWithin: 'Urgent — stockout ≤',
  urgentStockoutNow: 'Urgent — stockout imminent',
  // T-QA1 a11y: freshness-dot labels (wording matches the ghost age pill).
  leadTimeFreshLabel: 'lead time fresh',
  leadTimeStaleLabel: 'lead time',
  // T-R1: round-1 user feedback.
  hintOrderQty: 'Quantity to cover the target days of stock after arrival (default 45 d)',
  hintMoneyAtRisk: 'Profit lost to the stockout gap if you order today (gap days × daily profit)',
  sortLabel: 'Sort by',
  sortMostUrgent: 'Most urgent',
  noSupplier: 'No supplier',
  listingsSuffix: 'listings',
  // D3 — quiet source-freshness surfacing in the header.
  salesDataThrough: 'Sales data through',
  salesDataDelayedAlert: 'Sellerboard data delayed — latest sales through',
  // F1 — sparse rolling velocity wears the estimate pill: "estimate — N of 30 days observed".
  estimateObservedPrefix: 'estimate —',
  observedOf30DaysSuffix: 'of 30 days observed',
} as const;

export type DashboardTextKey = keyof typeof TEXT;

/**
 * Known reason-code -> friendly label map (QA polish item 3). Unknown codes
 * fall back to the raw code so nothing ever breaks on new gold vocabulary.
 */
export const REASON_CODE_LABELS: Record<string, string> = {
  frozen_family_target_review: TEXT.reasonFrozenFamilyTargetReview,
  missing_or_invalid_baseline_evidence: TEXT.reasonMissingBaselineEvidence,
  family_review_required: TEXT.reasonFamilyReviewRequired,
  untiered_projected: TEXT.badgeUntieredProjected,
  // T3/T7: approved D2 membership — fallback-velocity families in Supply Action.
  estimated_velocity_reorder_due: TEXT.reasonEstimatedVelocity,
};

export function reasonLabel(code: string, t: (key: string) => string): string {
  const label = REASON_CODE_LABELS[code];
  return label ? t(label) : code;
}

/** Every literal the dashboard renders — the i18n parity test iterates this. */
export const DASHBOARD_I18N_KEYS: string[] = Object.values(TEXT);
